/**
 * @file can_lib.h
 *
 * @brief This header file was generated by cantools version 41.0.2 Tue Apr 21 21:43:03 2026.
 *
 * @copyright Copyright (c) 2018-2019 Erik Moqvist
 *
 * @par License
 * The MIT License (MIT)
 *
 * Permission is hereby granted, free of charge, to any person
 * obtaining a copy of this software and associated documentation
 * files (the "Software"), to deal in the Software without
 * restriction, including without limitation the rights to use, copy,
 * modify, merge, publish, distribute, sublicense, and/or sell copies
 * of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be
 * included in all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 * NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS
 * BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN
 * ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
 * CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

#ifndef CAN_LIB_H
#define CAN_LIB_H

#ifdef __cplusplus
extern "C" {
#endif

#include <stdint.h>
#include <stdbool.h>
#include <stddef.h>

#ifndef EINVAL
#    define EINVAL 22
#endif

/* Frame ids. */
#define CAN_LIB_MSG1_FRAME_ID (0x1f4e5201u)
#define CAN_LIB_MSG2_FRAME_ID (0x1f4e5301u)
#define CAN_LIB_MSG3_FRAME_ID (0x1f4e5401u)
#define CAN_LIB_THRUST_FRAME_ID (0x4e8401u)
#define CAN_LIB_THRUST_SHORT_FRAME_ID (0x4e8401u)
#define CAN_LIB_BMS_STATUS_FRAME_ID (0x1000u)
#define CAN_LIB_BMS_STATUS_B_FRAME_ID (0x88u)
#define CAN_LIB_BMS_STATUS_B_EX_FRAME_ID (0x1100u)
#define CAN_LIB_BMS_STATUS_B_EX_E_FRAME_ID (0x1103u)
#define CAN_LIB_CHARGER_STATUS_FRAME_ID (0x100u)

/* Frame lengths in bytes. */
#define CAN_LIB_MSG1_LENGTH (7u)
#define CAN_LIB_MSG2_LENGTH (6u)
#define CAN_LIB_MSG3_LENGTH (8u)
#define CAN_LIB_THRUST_LENGTH (8u)
#define CAN_LIB_THRUST_SHORT_LENGTH (8u)
#define CAN_LIB_BMS_STATUS_LENGTH (7u)
#define CAN_LIB_BMS_STATUS_B_LENGTH (1u)
#define CAN_LIB_BMS_STATUS_B_EX_LENGTH (1u)
#define CAN_LIB_BMS_STATUS_B_EX_E_LENGTH (1u)
#define CAN_LIB_CHARGER_STATUS_LENGTH (6u)

/* Extended or standard frame types. */
#define CAN_LIB_MSG1_IS_EXTENDED (1)
#define CAN_LIB_MSG2_IS_EXTENDED (1)
#define CAN_LIB_MSG3_IS_EXTENDED (1)
#define CAN_LIB_THRUST_IS_EXTENDED (1)
#define CAN_LIB_THRUST_SHORT_IS_EXTENDED (1)
#define CAN_LIB_BMS_STATUS_IS_EXTENDED (1)
#define CAN_LIB_BMS_STATUS_B_IS_EXTENDED (0)
#define CAN_LIB_BMS_STATUS_B_EX_IS_EXTENDED (1)
#define CAN_LIB_BMS_STATUS_B_EX_E_IS_EXTENDED (1)
#define CAN_LIB_CHARGER_STATUS_IS_EXTENDED (0)

/* Frame cycle times in milliseconds. */


/* Signal choices. */


/* Frame Names. */
#define CAN_LIB_MSG1_NAME "msg1"
#define CAN_LIB_MSG2_NAME "msg2"
#define CAN_LIB_MSG3_NAME "msg3"
#define CAN_LIB_THRUST_NAME "thrust"
#define CAN_LIB_THRUST_SHORT_NAME "thrustShort"
#define CAN_LIB_BMS_STATUS_NAME "bms_status"
#define CAN_LIB_BMS_STATUS_B_NAME "bms_status_b"
#define CAN_LIB_BMS_STATUS_B_EX_NAME "bms_status_b_ex"
#define CAN_LIB_BMS_STATUS_B_EX_E_NAME "bms_status_b_ex_e"
#define CAN_LIB_CHARGER_STATUS_NAME "charger_status"

/* Signal Names. */
#define CAN_LIB_MSG1_RPM_NAME "RPM"
#define CAN_LIB_MSG1_PWM_NAME "PWM"
#define CAN_LIB_MSG1_OVERVOLTAGE_NAME "Overvoltage"
#define CAN_LIB_MSG1_UNDERVOLTAGE_NAME "Undervoltage"
#define CAN_LIB_MSG1_OVERCURRENT_NAME "Overcurrent"
#define CAN_LIB_MSG1_POSITIONING_COMPLETE_NAME "PositioningComplete"
#define CAN_LIB_MSG1_THROTTLE_LOST_NAME "ThrottleLost"
#define CAN_LIB_MSG1_THROTTLE_NOT_ZERO_NAME "ThrottleNotZero"
#define CAN_LIB_MSG1_MOS_OVERHEAT_NAME "MosOverheat"
#define CAN_LIB_MSG1_CAPACITOR_OVERHEAT_NAME "CapacitorOverheat"
#define CAN_LIB_MSG1_STALL_NAME "Stall"
#define CAN_LIB_MSG1_MOS_OPEN_NAME "MosOpen"
#define CAN_LIB_MSG1_MOS_SHORT_CIRCUIT_NAME "MosShortCircuit"
#define CAN_LIB_MSG1_MOTOR_DISCONNECTION_NAME "MotorDisconnection"
#define CAN_LIB_MSG1_OP_AMP_EXCEPTION_NAME "OpAmpException"
#define CAN_LIB_MSG1_COMM_STATUS_NAME "CommStatus"
#define CAN_LIB_MSG1_DIRECTION_FLAG_NAME "DirectionFlag"
#define CAN_LIB_MSG1_THROTTLE_SOURCE_NAME "ThrottleSource"
#define CAN_LIB_MSG1_TAIL_BYTE_NAME "TailByte"
#define CAN_LIB_MSG2_VOLTAGE_NAME "Voltage"
#define CAN_LIB_MSG2_CURRENT_NAME "Current"
#define CAN_LIB_MSG2_TEMPERATURE_NAME "Temperature"
#define CAN_LIB_MSG2_TAIL_BYTE_NAME "TailByte"
#define CAN_LIB_MSG3_MOS_T_NAME "MOS_T"
#define CAN_LIB_MSG3_CAP_T_NAME "CAP_T"
#define CAN_LIB_MSG3_MOTOR_T_NAME "Motor_T"
#define CAN_LIB_MSG3_RESERVED1_NAME "Reserved1"
#define CAN_LIB_MSG3_RESERVED2_NAME "Reserved2"
#define CAN_LIB_MSG3_RESERVED3_NAME "Reserved3"
#define CAN_LIB_MSG3_RESERVED4_NAME "Reserved4"
#define CAN_LIB_MSG3_TAIL_BYTE_NAME "TailByte"
#define CAN_LIB_THRUST_B1_NAME "b1"
#define CAN_LIB_THRUST_B2_NAME "b2"
#define CAN_LIB_THRUST_B3_NAME "b3"
#define CAN_LIB_THRUST_B4_NAME "b4"
#define CAN_LIB_THRUST_B5_NAME "b5"
#define CAN_LIB_THRUST_B6_NAME "b6"
#define CAN_LIB_THRUST_B7_NAME "b7"
#define CAN_LIB_THRUST_TAIL_BYTE_NAME "TailByte"
#define CAN_LIB_THRUST_SHORT_B1_NAME "b1"
#define CAN_LIB_THRUST_SHORT_B2_NAME "b2"
#define CAN_LIB_THRUST_SHORT_TAIL_BYTE_NAME "TailByte"
#define CAN_LIB_BMS_STATUS_BMS_STATE_NAME "bms_state"
#define CAN_LIB_BMS_STATUS_BMS_FAULT_CODE_NAME "bms_fault_code"
#define CAN_LIB_BMS_STATUS_PACK_VOLTAGE_NAME "pack_voltage"
#define CAN_LIB_BMS_STATUS_PACK_CURRENT_NAME "pack_current"
#define CAN_LIB_BMS_STATUS_CELL_BALANCING_STATUS_NAME "cell_balancing_status"
#define CAN_LIB_BMS_STATUS_REGEN_ENABLED_NAME "regen_enabled"
#define CAN_LIB_BMS_STATUS_OVERCURRENT_DETECT_NAME "overcurrent_detect"
#define CAN_LIB_BMS_STATUS_B_BMS_STATE_B_NAME "bms_state_b"
#define CAN_LIB_BMS_STATUS_B_EX_BMS_STATE_B_NAME "bms_state_b"
#define CAN_LIB_BMS_STATUS_B_EX_E_BMS_STATE_B_NAME "bms_state_b"
#define CAN_LIB_CHARGER_STATUS_CHARGER_STATE_NAME "charger_state"
#define CAN_LIB_CHARGER_STATUS_VOLTAGE_TARGET_NAME "voltage_target"
#define CAN_LIB_CHARGER_STATUS_OUTPUT_VOLTAGE_NAME "output_voltage"
#define CAN_LIB_CHARGER_STATUS_OUTPUT_CURRENT_NAME "output_current"

/**
 * Signals in message msg1.
 *
 * All signal values are as on the CAN bus.
 */
struct can_lib_msg1_t {
    /**
     * Range: 0..65535 (0..65535 rpm)
     * Scale: 1
     * Offset: 0
     */
    uint16_t rpm;

    /**
     * Range: 0..8191 (0..8191 -)
     * Scale: 1
     * Offset: 0
     */
    uint16_t pwm;

    /**
     * Range: 0..1 (0..1 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t overvoltage;

    /**
     * Range: 0..1 (0..1 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t undervoltage;

    /**
     * Range: 0..1 (0..1 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t overcurrent;

    /**
     * Range: 0..1 (0..1 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t positioning_complete;

    /**
     * Range: 0..1 (0..1 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t throttle_lost;

    /**
     * Range: 0..1 (0..1 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t throttle_not_zero;

    /**
     * Range: 0..1 (0..1 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t mos_overheat;

    /**
     * Range: 0..1 (0..1 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t capacitor_overheat;

    /**
     * Range: 0..1 (0..1 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t stall;

    /**
     * Range: 0..1 (0..1 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t mos_open;

    /**
     * Range: 0..1 (0..1 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t mos_short_circuit;

    /**
     * Range: 0..1 (0..1 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t motor_disconnection;

    /**
     * Range: 0..1 (0..1 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t op_amp_exception;

    /**
     * Range: 0..1 (0..1 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t comm_status;

    /**
     * Range: 0..1 (0..1 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t direction_flag;

    /**
     * Range: 0..1 (0..1 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t throttle_source;

    /**
     * Range: 0..255 (0..255 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t tail_byte;
};

/**
 * Signals in message msg2.
 *
 * All signal values are as on the CAN bus.
 */
struct can_lib_msg2_t {
    /**
     * Range: 0..65535 (0..6553.5 V)
     * Scale: 0.1
     * Offset: 0
     */
    uint16_t voltage;

    /**
     * Range: 0..65535 (0..6553.5 A)
     * Scale: 0.1
     * Offset: 0
     */
    uint16_t current;

    /**
     * Range: 0..255 (0..255 degC)
     * Scale: 1
     * Offset: 0
     */
    uint8_t temperature;

    /**
     * Range: 0..255 (0..255 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t tail_byte;
};

/**
 * Signals in message msg3.
 *
 * All signal values are as on the CAN bus.
 */
struct can_lib_msg3_t {
    /**
     * Range: 0..255 (0..255 degC)
     * Scale: 1
     * Offset: 0
     */
    uint8_t mos_t;

    /**
     * Range: 0..255 (0..255 degC)
     * Scale: 1
     * Offset: 0
     */
    uint8_t cap_t;

    /**
     * Range: 0..255 (0..255 degC)
     * Scale: 1
     * Offset: 0
     */
    uint8_t motor_t;

    /**
     * Range: 0..255 (0..255 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t reserved1;

    /**
     * Range: 0..255 (0..255 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t reserved2;

    /**
     * Range: 0..255 (0..255 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t reserved3;

    /**
     * Range: 0..255 (0..255 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t reserved4;

    /**
     * Range: 0..255 (0..255 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t tail_byte;
};

/**
 * Signals in message thrust.
 *
 * All signal values are as on the CAN bus.
 */
struct can_lib_thrust_t {
    /**
     * Range: 0..255 (0..255 tcode)
     * Scale: 1
     * Offset: 0
     */
    uint8_t b1;

    /**
     * Range: 0..255 (0..255 tcode)
     * Scale: 1
     * Offset: 0
     */
    uint8_t b2;

    /**
     * Range: 0..255 (0..255 tcode)
     * Scale: 1
     * Offset: 0
     */
    uint8_t b3;

    /**
     * Range: 0..255 (0..255 tcode)
     * Scale: 1
     * Offset: 0
     */
    uint8_t b4;

    /**
     * Range: 0..255 (0..255 tcode)
     * Scale: 1
     * Offset: 0
     */
    uint8_t b5;

    /**
     * Range: 0..255 (0..255 tcode)
     * Scale: 1
     * Offset: 0
     */
    uint8_t b6;

    /**
     * Range: 0..255 (0..255 tcode)
     * Scale: 1
     * Offset: 0
     */
    uint8_t b7;

    /**
     * Range: 0..255 (0..255 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t tail_byte;
};

/**
 * Signals in message thrustShort.
 *
 * All signal values are as on the CAN bus.
 */
struct can_lib_thrust_short_t {
    /**
     * Range: 0..255 (0..255 tcode)
     * Scale: 1
     * Offset: 0
     */
    uint8_t b1;

    /**
     * Range: 0..255 (0..255 tcode)
     * Scale: 1
     * Offset: 0
     */
    uint8_t b2;

    /**
     * Range: 0..255 (0..255 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t tail_byte;
};

/**
 * Signals in message bms_status.
 *
 * All signal values are as on the CAN bus.
 */
struct can_lib_bms_status_t {
    /**
     * Range: -
     * Scale: 1
     * Offset: 0
     */
    uint8_t bms_state;

    /**
     * Range: -
     * Scale: 1
     * Offset: 0
     */
    uint16_t bms_fault_code;

    /**
     * Range: -
     * Scale: 1
     * Offset: 0
     */
    uint16_t pack_voltage;

    /**
     * Range: -
     * Scale: 1
     * Offset: 0
     */
    int16_t pack_current;

    /**
     * Range: -
     * Scale: 1
     * Offset: 0
     */
    uint8_t cell_balancing_status;

    /**
     * Range: -
     * Scale: 1
     * Offset: 0
     */
    uint8_t regen_enabled;

    /**
     * Range: -
     * Scale: 1
     * Offset: 0
     */
    uint8_t overcurrent_detect;
};

/**
 * Signals in message bms_status_b.
 *
 * All signal values are as on the CAN bus.
 */
struct can_lib_bms_status_b_t {
    /**
     * Range: -
     * Scale: 1
     * Offset: 0
     */
    uint8_t bms_state_b;
};

/**
 * Signals in message bms_status_b_ex.
 *
 * All signal values are as on the CAN bus.
 */
struct can_lib_bms_status_b_ex_t {
    /**
     * Range: -
     * Scale: 1
     * Offset: 0
     */
    uint8_t bms_state_b;
};

/**
 * Signals in message bms_status_b_ex_e.
 *
 * All signal values are as on the CAN bus.
 */
struct can_lib_bms_status_b_ex_e_t {
    /**
     * Range: -
     * Scale: 1
     * Offset: 0
     */
    uint8_t bms_state_b;
};

/**
 * Signals in message charger_status.
 *
 * All signal values are as on the CAN bus.
 */
struct can_lib_charger_status_t {
    /**
     * Range: -
     * Scale: 1
     * Offset: 0
     */
    uint8_t charger_state;

    /**
     * Range: 0..70 (0..70 -)
     * Scale: 1
     * Offset: 0
     */
    uint16_t voltage_target;

    /**
     * Range: 0..70 (0.0..70.0 -)
     * Scale: 1
     * Offset: 0
     */
    uint16_t output_voltage;

    /**
     * Range: 0..100 (0.0..100.0 -)
     * Scale: 1
     * Offset: 0
     */
    uint16_t output_current;
};

/**
 * Pack message msg1.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int can_lib_msg1_pack(
    uint8_t *dst_p,
    const struct can_lib_msg1_t *src_p,
    size_t size);

/**
 * Unpack message msg1.
 *
 * @param[out] dst_p Object to unpack the message into.
 * @param[in] src_p Message to unpack.
 * @param[in] size Size of src_p.
 *
 * @return zero(0) or negative error code.
 */
int can_lib_msg1_unpack(
    struct can_lib_msg1_t *dst_p,
    const uint8_t *src_p,
    size_t size);

/**
 * Init message fields to default values from msg1.
 *
 * @param[in] msg_p Message to init.
 *
 * @return zero(0) on success or (-1) in case of nullptr argument.
 */
int can_lib_msg1_init(struct can_lib_msg1_t *msg_p);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint16_t can_lib_msg1_rpm_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double can_lib_msg1_rpm_decode(uint16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool can_lib_msg1_rpm_is_in_range(uint16_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint16_t can_lib_msg1_pwm_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double can_lib_msg1_pwm_decode(uint16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool can_lib_msg1_pwm_is_in_range(uint16_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t can_lib_msg1_overvoltage_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double can_lib_msg1_overvoltage_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool can_lib_msg1_overvoltage_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t can_lib_msg1_undervoltage_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double can_lib_msg1_undervoltage_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool can_lib_msg1_undervoltage_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t can_lib_msg1_overcurrent_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double can_lib_msg1_overcurrent_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool can_lib_msg1_overcurrent_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t can_lib_msg1_positioning_complete_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double can_lib_msg1_positioning_complete_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool can_lib_msg1_positioning_complete_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t can_lib_msg1_throttle_lost_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double can_lib_msg1_throttle_lost_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool can_lib_msg1_throttle_lost_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t can_lib_msg1_throttle_not_zero_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double can_lib_msg1_throttle_not_zero_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool can_lib_msg1_throttle_not_zero_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t can_lib_msg1_mos_overheat_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double can_lib_msg1_mos_overheat_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool can_lib_msg1_mos_overheat_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t can_lib_msg1_capacitor_overheat_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double can_lib_msg1_capacitor_overheat_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool can_lib_msg1_capacitor_overheat_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t can_lib_msg1_stall_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double can_lib_msg1_stall_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool can_lib_msg1_stall_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t can_lib_msg1_mos_open_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double can_lib_msg1_mos_open_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool can_lib_msg1_mos_open_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t can_lib_msg1_mos_short_circuit_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double can_lib_msg1_mos_short_circuit_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool can_lib_msg1_mos_short_circuit_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t can_lib_msg1_motor_disconnection_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double can_lib_msg1_motor_disconnection_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool can_lib_msg1_motor_disconnection_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t can_lib_msg1_op_amp_exception_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double can_lib_msg1_op_amp_exception_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool can_lib_msg1_op_amp_exception_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t can_lib_msg1_comm_status_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double can_lib_msg1_comm_status_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool can_lib_msg1_comm_status_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t can_lib_msg1_direction_flag_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double can_lib_msg1_direction_flag_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool can_lib_msg1_direction_flag_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t can_lib_msg1_throttle_source_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double can_lib_msg1_throttle_source_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool can_lib_msg1_throttle_source_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t can_lib_msg1_tail_byte_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double can_lib_msg1_tail_byte_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool can_lib_msg1_tail_byte_is_in_range(uint8_t value);

/**
 * Pack message msg2.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int can_lib_msg2_pack(
    uint8_t *dst_p,
    const struct can_lib_msg2_t *src_p,
    size_t size);

/**
 * Unpack message msg2.
 *
 * @param[out] dst_p Object to unpack the message into.
 * @param[in] src_p Message to unpack.
 * @param[in] size Size of src_p.
 *
 * @return zero(0) or negative error code.
 */
int can_lib_msg2_unpack(
    struct can_lib_msg2_t *dst_p,
    const uint8_t *src_p,
    size_t size);

/**
 * Init message fields to default values from msg2.
 *
 * @param[in] msg_p Message to init.
 *
 * @return zero(0) on success or (-1) in case of nullptr argument.
 */
int can_lib_msg2_init(struct can_lib_msg2_t *msg_p);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint16_t can_lib_msg2_voltage_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double can_lib_msg2_voltage_decode(uint16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool can_lib_msg2_voltage_is_in_range(uint16_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint16_t can_lib_msg2_current_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double can_lib_msg2_current_decode(uint16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool can_lib_msg2_current_is_in_range(uint16_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t can_lib_msg2_temperature_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double can_lib_msg2_temperature_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool can_lib_msg2_temperature_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t can_lib_msg2_tail_byte_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double can_lib_msg2_tail_byte_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool can_lib_msg2_tail_byte_is_in_range(uint8_t value);

/**
 * Pack message msg3.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int can_lib_msg3_pack(
    uint8_t *dst_p,
    const struct can_lib_msg3_t *src_p,
    size_t size);

/**
 * Unpack message msg3.
 *
 * @param[out] dst_p Object to unpack the message into.
 * @param[in] src_p Message to unpack.
 * @param[in] size Size of src_p.
 *
 * @return zero(0) or negative error code.
 */
int can_lib_msg3_unpack(
    struct can_lib_msg3_t *dst_p,
    const uint8_t *src_p,
    size_t size);

/**
 * Init message fields to default values from msg3.
 *
 * @param[in] msg_p Message to init.
 *
 * @return zero(0) on success or (-1) in case of nullptr argument.
 */
int can_lib_msg3_init(struct can_lib_msg3_t *msg_p);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t can_lib_msg3_mos_t_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double can_lib_msg3_mos_t_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool can_lib_msg3_mos_t_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t can_lib_msg3_cap_t_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double can_lib_msg3_cap_t_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool can_lib_msg3_cap_t_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t can_lib_msg3_motor_t_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double can_lib_msg3_motor_t_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool can_lib_msg3_motor_t_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t can_lib_msg3_reserved1_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double can_lib_msg3_reserved1_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool can_lib_msg3_reserved1_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t can_lib_msg3_reserved2_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double can_lib_msg3_reserved2_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool can_lib_msg3_reserved2_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t can_lib_msg3_reserved3_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double can_lib_msg3_reserved3_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool can_lib_msg3_reserved3_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t can_lib_msg3_reserved4_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double can_lib_msg3_reserved4_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool can_lib_msg3_reserved4_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t can_lib_msg3_tail_byte_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double can_lib_msg3_tail_byte_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool can_lib_msg3_tail_byte_is_in_range(uint8_t value);

/**
 * Pack message thrust.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int can_lib_thrust_pack(
    uint8_t *dst_p,
    const struct can_lib_thrust_t *src_p,
    size_t size);

/**
 * Unpack message thrust.
 *
 * @param[out] dst_p Object to unpack the message into.
 * @param[in] src_p Message to unpack.
 * @param[in] size Size of src_p.
 *
 * @return zero(0) or negative error code.
 */
int can_lib_thrust_unpack(
    struct can_lib_thrust_t *dst_p,
    const uint8_t *src_p,
    size_t size);

/**
 * Init message fields to default values from thrust.
 *
 * @param[in] msg_p Message to init.
 *
 * @return zero(0) on success or (-1) in case of nullptr argument.
 */
int can_lib_thrust_init(struct can_lib_thrust_t *msg_p);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t can_lib_thrust_b1_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double can_lib_thrust_b1_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool can_lib_thrust_b1_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t can_lib_thrust_b2_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double can_lib_thrust_b2_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool can_lib_thrust_b2_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t can_lib_thrust_b3_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double can_lib_thrust_b3_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool can_lib_thrust_b3_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t can_lib_thrust_b4_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double can_lib_thrust_b4_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool can_lib_thrust_b4_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t can_lib_thrust_b5_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double can_lib_thrust_b5_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool can_lib_thrust_b5_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t can_lib_thrust_b6_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double can_lib_thrust_b6_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool can_lib_thrust_b6_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t can_lib_thrust_b7_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double can_lib_thrust_b7_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool can_lib_thrust_b7_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t can_lib_thrust_tail_byte_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double can_lib_thrust_tail_byte_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool can_lib_thrust_tail_byte_is_in_range(uint8_t value);

/**
 * Pack message thrustShort.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int can_lib_thrust_short_pack(
    uint8_t *dst_p,
    const struct can_lib_thrust_short_t *src_p,
    size_t size);

/**
 * Unpack message thrustShort.
 *
 * @param[out] dst_p Object to unpack the message into.
 * @param[in] src_p Message to unpack.
 * @param[in] size Size of src_p.
 *
 * @return zero(0) or negative error code.
 */
int can_lib_thrust_short_unpack(
    struct can_lib_thrust_short_t *dst_p,
    const uint8_t *src_p,
    size_t size);

/**
 * Init message fields to default values from thrustShort.
 *
 * @param[in] msg_p Message to init.
 *
 * @return zero(0) on success or (-1) in case of nullptr argument.
 */
int can_lib_thrust_short_init(struct can_lib_thrust_short_t *msg_p);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t can_lib_thrust_short_b1_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double can_lib_thrust_short_b1_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool can_lib_thrust_short_b1_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t can_lib_thrust_short_b2_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double can_lib_thrust_short_b2_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool can_lib_thrust_short_b2_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t can_lib_thrust_short_tail_byte_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double can_lib_thrust_short_tail_byte_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool can_lib_thrust_short_tail_byte_is_in_range(uint8_t value);

/**
 * Pack message bms_status.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int can_lib_bms_status_pack(
    uint8_t *dst_p,
    const struct can_lib_bms_status_t *src_p,
    size_t size);

/**
 * Unpack message bms_status.
 *
 * @param[out] dst_p Object to unpack the message into.
 * @param[in] src_p Message to unpack.
 * @param[in] size Size of src_p.
 *
 * @return zero(0) or negative error code.
 */
int can_lib_bms_status_unpack(
    struct can_lib_bms_status_t *dst_p,
    const uint8_t *src_p,
    size_t size);

/**
 * Init message fields to default values from bms_status.
 *
 * @param[in] msg_p Message to init.
 *
 * @return zero(0) on success or (-1) in case of nullptr argument.
 */
int can_lib_bms_status_init(struct can_lib_bms_status_t *msg_p);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t can_lib_bms_status_bms_state_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double can_lib_bms_status_bms_state_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool can_lib_bms_status_bms_state_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint16_t can_lib_bms_status_bms_fault_code_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double can_lib_bms_status_bms_fault_code_decode(uint16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool can_lib_bms_status_bms_fault_code_is_in_range(uint16_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint16_t can_lib_bms_status_pack_voltage_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double can_lib_bms_status_pack_voltage_decode(uint16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool can_lib_bms_status_pack_voltage_is_in_range(uint16_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
int16_t can_lib_bms_status_pack_current_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double can_lib_bms_status_pack_current_decode(int16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool can_lib_bms_status_pack_current_is_in_range(int16_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t can_lib_bms_status_cell_balancing_status_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double can_lib_bms_status_cell_balancing_status_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool can_lib_bms_status_cell_balancing_status_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t can_lib_bms_status_regen_enabled_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double can_lib_bms_status_regen_enabled_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool can_lib_bms_status_regen_enabled_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t can_lib_bms_status_overcurrent_detect_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double can_lib_bms_status_overcurrent_detect_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool can_lib_bms_status_overcurrent_detect_is_in_range(uint8_t value);

/**
 * Pack message bms_status_b.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int can_lib_bms_status_b_pack(
    uint8_t *dst_p,
    const struct can_lib_bms_status_b_t *src_p,
    size_t size);

/**
 * Unpack message bms_status_b.
 *
 * @param[out] dst_p Object to unpack the message into.
 * @param[in] src_p Message to unpack.
 * @param[in] size Size of src_p.
 *
 * @return zero(0) or negative error code.
 */
int can_lib_bms_status_b_unpack(
    struct can_lib_bms_status_b_t *dst_p,
    const uint8_t *src_p,
    size_t size);

/**
 * Init message fields to default values from bms_status_b.
 *
 * @param[in] msg_p Message to init.
 *
 * @return zero(0) on success or (-1) in case of nullptr argument.
 */
int can_lib_bms_status_b_init(struct can_lib_bms_status_b_t *msg_p);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t can_lib_bms_status_b_bms_state_b_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double can_lib_bms_status_b_bms_state_b_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool can_lib_bms_status_b_bms_state_b_is_in_range(uint8_t value);

/**
 * Pack message bms_status_b_ex.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int can_lib_bms_status_b_ex_pack(
    uint8_t *dst_p,
    const struct can_lib_bms_status_b_ex_t *src_p,
    size_t size);

/**
 * Unpack message bms_status_b_ex.
 *
 * @param[out] dst_p Object to unpack the message into.
 * @param[in] src_p Message to unpack.
 * @param[in] size Size of src_p.
 *
 * @return zero(0) or negative error code.
 */
int can_lib_bms_status_b_ex_unpack(
    struct can_lib_bms_status_b_ex_t *dst_p,
    const uint8_t *src_p,
    size_t size);

/**
 * Init message fields to default values from bms_status_b_ex.
 *
 * @param[in] msg_p Message to init.
 *
 * @return zero(0) on success or (-1) in case of nullptr argument.
 */
int can_lib_bms_status_b_ex_init(struct can_lib_bms_status_b_ex_t *msg_p);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t can_lib_bms_status_b_ex_bms_state_b_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double can_lib_bms_status_b_ex_bms_state_b_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool can_lib_bms_status_b_ex_bms_state_b_is_in_range(uint8_t value);

/**
 * Pack message bms_status_b_ex_e.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int can_lib_bms_status_b_ex_e_pack(
    uint8_t *dst_p,
    const struct can_lib_bms_status_b_ex_e_t *src_p,
    size_t size);

/**
 * Unpack message bms_status_b_ex_e.
 *
 * @param[out] dst_p Object to unpack the message into.
 * @param[in] src_p Message to unpack.
 * @param[in] size Size of src_p.
 *
 * @return zero(0) or negative error code.
 */
int can_lib_bms_status_b_ex_e_unpack(
    struct can_lib_bms_status_b_ex_e_t *dst_p,
    const uint8_t *src_p,
    size_t size);

/**
 * Init message fields to default values from bms_status_b_ex_e.
 *
 * @param[in] msg_p Message to init.
 *
 * @return zero(0) on success or (-1) in case of nullptr argument.
 */
int can_lib_bms_status_b_ex_e_init(struct can_lib_bms_status_b_ex_e_t *msg_p);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t can_lib_bms_status_b_ex_e_bms_state_b_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double can_lib_bms_status_b_ex_e_bms_state_b_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool can_lib_bms_status_b_ex_e_bms_state_b_is_in_range(uint8_t value);

/**
 * Pack message charger_status.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int can_lib_charger_status_pack(
    uint8_t *dst_p,
    const struct can_lib_charger_status_t *src_p,
    size_t size);

/**
 * Unpack message charger_status.
 *
 * @param[out] dst_p Object to unpack the message into.
 * @param[in] src_p Message to unpack.
 * @param[in] size Size of src_p.
 *
 * @return zero(0) or negative error code.
 */
int can_lib_charger_status_unpack(
    struct can_lib_charger_status_t *dst_p,
    const uint8_t *src_p,
    size_t size);

/**
 * Init message fields to default values from charger_status.
 *
 * @param[in] msg_p Message to init.
 *
 * @return zero(0) on success or (-1) in case of nullptr argument.
 */
int can_lib_charger_status_init(struct can_lib_charger_status_t *msg_p);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t can_lib_charger_status_charger_state_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double can_lib_charger_status_charger_state_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool can_lib_charger_status_charger_state_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint16_t can_lib_charger_status_voltage_target_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double can_lib_charger_status_voltage_target_decode(uint16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool can_lib_charger_status_voltage_target_is_in_range(uint16_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint16_t can_lib_charger_status_output_voltage_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double can_lib_charger_status_output_voltage_decode(uint16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool can_lib_charger_status_output_voltage_is_in_range(uint16_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint16_t can_lib_charger_status_output_current_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double can_lib_charger_status_output_current_decode(uint16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool can_lib_charger_status_output_current_is_in_range(uint16_t value);


#ifdef __cplusplus
}
#endif

#endif
