/**
 * @file can_lib.c
 *
 * @brief This source file was generated by cantools version 41.3.1 Sat May  2 20:31:27 2026.
 *
 * @copyright Copyright (c) 2018-2019 Erik Moqvist
 *
 * @par License
 * The MIT License (MIT)
 *
 * Permission is hereby granted, free of charge, to any person
 * obtaining a copy of this software and associated documentation
 * files (the "Software"), to deal in the Software without
 * restriction, including without limitation the rights to use, copy,
 * modify, merge, publish, distribute, sublicense, and/or sell copies
 * of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be
 * included in all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 * NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS
 * BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN
 * ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
 * CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

#include <string.h>

#include "can_lib.h"

static inline uint8_t pack_left_shift_u8(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value << shift) & mask);
}

static inline uint8_t pack_left_shift_u16(
    uint16_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value << shift) & mask);
}

static inline uint8_t pack_right_shift_u16(
    uint16_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value >> shift) & mask);
}

static inline uint16_t unpack_left_shift_u16(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint16_t)((uint16_t)(value & mask) << shift);
}

static inline uint8_t unpack_right_shift_u8(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value & mask) >> shift);
}

static inline uint16_t unpack_right_shift_u16(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint16_t)((uint16_t)(value & mask) >> shift);
}

int can_lib_msg1_pack(
    uint8_t *dst_p,
    const struct can_lib_msg1_t *src_p,
    size_t size)
{
    if (size < 7u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 7);

    dst_p[0] |= pack_left_shift_u16(src_p->rpm, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u16(src_p->rpm, 8u, 0xffu);
    dst_p[2] |= pack_left_shift_u16(src_p->pwm, 0u, 0xffu);
    dst_p[3] |= pack_right_shift_u16(src_p->pwm, 8u, 0xffu);
    dst_p[4] |= pack_left_shift_u8(src_p->overvoltage, 0u, 0x01u);
    dst_p[4] |= pack_left_shift_u8(src_p->undervoltage, 1u, 0x02u);
    dst_p[4] |= pack_left_shift_u8(src_p->overcurrent, 2u, 0x04u);
    dst_p[4] |= pack_left_shift_u8(src_p->positioning_complete, 3u, 0x08u);
    dst_p[4] |= pack_left_shift_u8(src_p->throttle_lost, 4u, 0x10u);
    dst_p[4] |= pack_left_shift_u8(src_p->throttle_not_zero, 5u, 0x20u);
    dst_p[4] |= pack_left_shift_u8(src_p->mos_overheat, 6u, 0x40u);
    dst_p[4] |= pack_left_shift_u8(src_p->capacitor_overheat, 7u, 0x80u);
    dst_p[5] |= pack_left_shift_u8(src_p->stall, 0u, 0x01u);
    dst_p[5] |= pack_left_shift_u8(src_p->mos_open, 1u, 0x02u);
    dst_p[5] |= pack_left_shift_u8(src_p->mos_short_circuit, 2u, 0x04u);
    dst_p[5] |= pack_left_shift_u8(src_p->motor_disconnection, 3u, 0x08u);
    dst_p[5] |= pack_left_shift_u8(src_p->op_amp_exception, 4u, 0x10u);
    dst_p[5] |= pack_left_shift_u8(src_p->comm_status, 5u, 0x20u);
    dst_p[5] |= pack_left_shift_u8(src_p->direction_flag, 6u, 0x40u);
    dst_p[5] |= pack_left_shift_u8(src_p->throttle_source, 7u, 0x80u);
    dst_p[6] |= pack_left_shift_u8(src_p->tail_byte, 0u, 0xffu);

    return (7);
}

int can_lib_msg1_unpack(
    struct can_lib_msg1_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 7u) {
        return (-EINVAL);
    }

    dst_p->rpm = unpack_right_shift_u16(src_p[0], 0u, 0xffu);
    dst_p->rpm |= unpack_left_shift_u16(src_p[1], 8u, 0xffu);
    dst_p->pwm = unpack_right_shift_u16(src_p[2], 0u, 0xffu);
    dst_p->pwm |= unpack_left_shift_u16(src_p[3], 8u, 0xffu);
    dst_p->overvoltage = unpack_right_shift_u8(src_p[4], 0u, 0x01u);
    dst_p->undervoltage = unpack_right_shift_u8(src_p[4], 1u, 0x02u);
    dst_p->overcurrent = unpack_right_shift_u8(src_p[4], 2u, 0x04u);
    dst_p->positioning_complete = unpack_right_shift_u8(src_p[4], 3u, 0x08u);
    dst_p->throttle_lost = unpack_right_shift_u8(src_p[4], 4u, 0x10u);
    dst_p->throttle_not_zero = unpack_right_shift_u8(src_p[4], 5u, 0x20u);
    dst_p->mos_overheat = unpack_right_shift_u8(src_p[4], 6u, 0x40u);
    dst_p->capacitor_overheat = unpack_right_shift_u8(src_p[4], 7u, 0x80u);
    dst_p->stall = unpack_right_shift_u8(src_p[5], 0u, 0x01u);
    dst_p->mos_open = unpack_right_shift_u8(src_p[5], 1u, 0x02u);
    dst_p->mos_short_circuit = unpack_right_shift_u8(src_p[5], 2u, 0x04u);
    dst_p->motor_disconnection = unpack_right_shift_u8(src_p[5], 3u, 0x08u);
    dst_p->op_amp_exception = unpack_right_shift_u8(src_p[5], 4u, 0x10u);
    dst_p->comm_status = unpack_right_shift_u8(src_p[5], 5u, 0x20u);
    dst_p->direction_flag = unpack_right_shift_u8(src_p[5], 6u, 0x40u);
    dst_p->throttle_source = unpack_right_shift_u8(src_p[5], 7u, 0x80u);
    dst_p->tail_byte = unpack_right_shift_u8(src_p[6], 0u, 0xffu);

    return (0);
}

int can_lib_msg1_init(struct can_lib_msg1_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct can_lib_msg1_t));

    return 0;
}

uint16_t can_lib_msg1_rpm_encode(double value)
{
    return (uint16_t)(value);
}

double can_lib_msg1_rpm_decode(uint16_t value)
{
    return ((double)value);
}

bool can_lib_msg1_rpm_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

bool can_lib_msg1_rpm_is_in_phys_range(double value)
{
    return ((value >= 0.0) && (value <= 65535.0));
}

uint16_t can_lib_msg1_pwm_encode(double value)
{
    return (uint16_t)(value);
}

double can_lib_msg1_pwm_decode(uint16_t value)
{
    return ((double)value);
}

bool can_lib_msg1_pwm_is_in_range(uint16_t value)
{
    return (value <= 8191u);
}

bool can_lib_msg1_pwm_is_in_phys_range(double value)
{
    return ((value >= 0.0) && (value <= 8191.0));
}

uint8_t can_lib_msg1_overvoltage_encode(double value)
{
    return (uint8_t)(value);
}

double can_lib_msg1_overvoltage_decode(uint8_t value)
{
    return ((double)value);
}

bool can_lib_msg1_overvoltage_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

bool can_lib_msg1_overvoltage_is_in_phys_range(double value)
{
    return ((value >= 0.0) && (value <= 1.0));
}

uint8_t can_lib_msg1_undervoltage_encode(double value)
{
    return (uint8_t)(value);
}

double can_lib_msg1_undervoltage_decode(uint8_t value)
{
    return ((double)value);
}

bool can_lib_msg1_undervoltage_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

bool can_lib_msg1_undervoltage_is_in_phys_range(double value)
{
    return ((value >= 0.0) && (value <= 1.0));
}

uint8_t can_lib_msg1_overcurrent_encode(double value)
{
    return (uint8_t)(value);
}

double can_lib_msg1_overcurrent_decode(uint8_t value)
{
    return ((double)value);
}

bool can_lib_msg1_overcurrent_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

bool can_lib_msg1_overcurrent_is_in_phys_range(double value)
{
    return ((value >= 0.0) && (value <= 1.0));
}

uint8_t can_lib_msg1_positioning_complete_encode(double value)
{
    return (uint8_t)(value);
}

double can_lib_msg1_positioning_complete_decode(uint8_t value)
{
    return ((double)value);
}

bool can_lib_msg1_positioning_complete_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

bool can_lib_msg1_positioning_complete_is_in_phys_range(double value)
{
    return ((value >= 0.0) && (value <= 1.0));
}

uint8_t can_lib_msg1_throttle_lost_encode(double value)
{
    return (uint8_t)(value);
}

double can_lib_msg1_throttle_lost_decode(uint8_t value)
{
    return ((double)value);
}

bool can_lib_msg1_throttle_lost_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

bool can_lib_msg1_throttle_lost_is_in_phys_range(double value)
{
    return ((value >= 0.0) && (value <= 1.0));
}

uint8_t can_lib_msg1_throttle_not_zero_encode(double value)
{
    return (uint8_t)(value);
}

double can_lib_msg1_throttle_not_zero_decode(uint8_t value)
{
    return ((double)value);
}

bool can_lib_msg1_throttle_not_zero_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

bool can_lib_msg1_throttle_not_zero_is_in_phys_range(double value)
{
    return ((value >= 0.0) && (value <= 1.0));
}

uint8_t can_lib_msg1_mos_overheat_encode(double value)
{
    return (uint8_t)(value);
}

double can_lib_msg1_mos_overheat_decode(uint8_t value)
{
    return ((double)value);
}

bool can_lib_msg1_mos_overheat_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

bool can_lib_msg1_mos_overheat_is_in_phys_range(double value)
{
    return ((value >= 0.0) && (value <= 1.0));
}

uint8_t can_lib_msg1_capacitor_overheat_encode(double value)
{
    return (uint8_t)(value);
}

double can_lib_msg1_capacitor_overheat_decode(uint8_t value)
{
    return ((double)value);
}

bool can_lib_msg1_capacitor_overheat_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

bool can_lib_msg1_capacitor_overheat_is_in_phys_range(double value)
{
    return ((value >= 0.0) && (value <= 1.0));
}

uint8_t can_lib_msg1_stall_encode(double value)
{
    return (uint8_t)(value);
}

double can_lib_msg1_stall_decode(uint8_t value)
{
    return ((double)value);
}

bool can_lib_msg1_stall_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

bool can_lib_msg1_stall_is_in_phys_range(double value)
{
    return ((value >= 0.0) && (value <= 1.0));
}

uint8_t can_lib_msg1_mos_open_encode(double value)
{
    return (uint8_t)(value);
}

double can_lib_msg1_mos_open_decode(uint8_t value)
{
    return ((double)value);
}

bool can_lib_msg1_mos_open_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

bool can_lib_msg1_mos_open_is_in_phys_range(double value)
{
    return ((value >= 0.0) && (value <= 1.0));
}

uint8_t can_lib_msg1_mos_short_circuit_encode(double value)
{
    return (uint8_t)(value);
}

double can_lib_msg1_mos_short_circuit_decode(uint8_t value)
{
    return ((double)value);
}

bool can_lib_msg1_mos_short_circuit_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

bool can_lib_msg1_mos_short_circuit_is_in_phys_range(double value)
{
    return ((value >= 0.0) && (value <= 1.0));
}

uint8_t can_lib_msg1_motor_disconnection_encode(double value)
{
    return (uint8_t)(value);
}

double can_lib_msg1_motor_disconnection_decode(uint8_t value)
{
    return ((double)value);
}

bool can_lib_msg1_motor_disconnection_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

bool can_lib_msg1_motor_disconnection_is_in_phys_range(double value)
{
    return ((value >= 0.0) && (value <= 1.0));
}

uint8_t can_lib_msg1_op_amp_exception_encode(double value)
{
    return (uint8_t)(value);
}

double can_lib_msg1_op_amp_exception_decode(uint8_t value)
{
    return ((double)value);
}

bool can_lib_msg1_op_amp_exception_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

bool can_lib_msg1_op_amp_exception_is_in_phys_range(double value)
{
    return ((value >= 0.0) && (value <= 1.0));
}

uint8_t can_lib_msg1_comm_status_encode(double value)
{
    return (uint8_t)(value);
}

double can_lib_msg1_comm_status_decode(uint8_t value)
{
    return ((double)value);
}

bool can_lib_msg1_comm_status_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

bool can_lib_msg1_comm_status_is_in_phys_range(double value)
{
    return ((value >= 0.0) && (value <= 1.0));
}

uint8_t can_lib_msg1_direction_flag_encode(double value)
{
    return (uint8_t)(value);
}

double can_lib_msg1_direction_flag_decode(uint8_t value)
{
    return ((double)value);
}

bool can_lib_msg1_direction_flag_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

bool can_lib_msg1_direction_flag_is_in_phys_range(double value)
{
    return ((value >= 0.0) && (value <= 1.0));
}

uint8_t can_lib_msg1_throttle_source_encode(double value)
{
    return (uint8_t)(value);
}

double can_lib_msg1_throttle_source_decode(uint8_t value)
{
    return ((double)value);
}

bool can_lib_msg1_throttle_source_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

bool can_lib_msg1_throttle_source_is_in_phys_range(double value)
{
    return ((value >= 0.0) && (value <= 1.0));
}

uint8_t can_lib_msg1_tail_byte_encode(double value)
{
    return (uint8_t)(value);
}

double can_lib_msg1_tail_byte_decode(uint8_t value)
{
    return ((double)value);
}

bool can_lib_msg1_tail_byte_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

bool can_lib_msg1_tail_byte_is_in_phys_range(double value)
{
    return ((value >= 0.0) && (value <= 255.0));
}

int can_lib_msg2_pack(
    uint8_t *dst_p,
    const struct can_lib_msg2_t *src_p,
    size_t size)
{
    if (size < 6u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 6);

    dst_p[0] |= pack_left_shift_u16(src_p->voltage, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u16(src_p->voltage, 8u, 0xffu);
    dst_p[2] |= pack_left_shift_u16(src_p->current, 0u, 0xffu);
    dst_p[3] |= pack_right_shift_u16(src_p->current, 8u, 0xffu);
    dst_p[4] |= pack_left_shift_u8(src_p->temperature, 0u, 0xffu);
    dst_p[5] |= pack_left_shift_u8(src_p->tail_byte, 0u, 0xffu);

    return (6);
}

int can_lib_msg2_unpack(
    struct can_lib_msg2_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 6u) {
        return (-EINVAL);
    }

    dst_p->voltage = unpack_right_shift_u16(src_p[0], 0u, 0xffu);
    dst_p->voltage |= unpack_left_shift_u16(src_p[1], 8u, 0xffu);
    dst_p->current = unpack_right_shift_u16(src_p[2], 0u, 0xffu);
    dst_p->current |= unpack_left_shift_u16(src_p[3], 8u, 0xffu);
    dst_p->temperature = unpack_right_shift_u8(src_p[4], 0u, 0xffu);
    dst_p->tail_byte = unpack_right_shift_u8(src_p[5], 0u, 0xffu);

    return (0);
}

int can_lib_msg2_init(struct can_lib_msg2_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct can_lib_msg2_t));

    return 0;
}

uint16_t can_lib_msg2_voltage_encode(double value)
{
    return (uint16_t)(value / 0.1);
}

double can_lib_msg2_voltage_decode(uint16_t value)
{
    return ((double)value * 0.1);
}

bool can_lib_msg2_voltage_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

bool can_lib_msg2_voltage_is_in_phys_range(double value)
{
    return ((value >= 0.0) && (value <= 6553.5));
}

uint16_t can_lib_msg2_current_encode(double value)
{
    return (uint16_t)(value / 0.1);
}

double can_lib_msg2_current_decode(uint16_t value)
{
    return ((double)value * 0.1);
}

bool can_lib_msg2_current_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

bool can_lib_msg2_current_is_in_phys_range(double value)
{
    return ((value >= 0.0) && (value <= 6553.5));
}

uint8_t can_lib_msg2_temperature_encode(double value)
{
    return (uint8_t)(value);
}

double can_lib_msg2_temperature_decode(uint8_t value)
{
    return ((double)value);
}

bool can_lib_msg2_temperature_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

bool can_lib_msg2_temperature_is_in_phys_range(double value)
{
    return ((value >= 0.0) && (value <= 255.0));
}

uint8_t can_lib_msg2_tail_byte_encode(double value)
{
    return (uint8_t)(value);
}

double can_lib_msg2_tail_byte_decode(uint8_t value)
{
    return ((double)value);
}

bool can_lib_msg2_tail_byte_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

bool can_lib_msg2_tail_byte_is_in_phys_range(double value)
{
    return ((value >= 0.0) && (value <= 255.0));
}

int can_lib_msg3_pack(
    uint8_t *dst_p,
    const struct can_lib_msg3_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_left_shift_u8(src_p->mos_t, 0u, 0xffu);
    dst_p[1] |= pack_left_shift_u8(src_p->cap_t, 0u, 0xffu);
    dst_p[2] |= pack_left_shift_u8(src_p->motor_t, 0u, 0xffu);
    dst_p[3] |= pack_left_shift_u8(src_p->reserved1, 0u, 0xffu);
    dst_p[4] |= pack_left_shift_u8(src_p->reserved2, 0u, 0xffu);
    dst_p[5] |= pack_left_shift_u8(src_p->reserved3, 0u, 0xffu);
    dst_p[6] |= pack_left_shift_u8(src_p->reserved4, 0u, 0xffu);
    dst_p[7] |= pack_left_shift_u8(src_p->tail_byte, 0u, 0xffu);

    return (8);
}

int can_lib_msg3_unpack(
    struct can_lib_msg3_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->mos_t = unpack_right_shift_u8(src_p[0], 0u, 0xffu);
    dst_p->cap_t = unpack_right_shift_u8(src_p[1], 0u, 0xffu);
    dst_p->motor_t = unpack_right_shift_u8(src_p[2], 0u, 0xffu);
    dst_p->reserved1 = unpack_right_shift_u8(src_p[3], 0u, 0xffu);
    dst_p->reserved2 = unpack_right_shift_u8(src_p[4], 0u, 0xffu);
    dst_p->reserved3 = unpack_right_shift_u8(src_p[5], 0u, 0xffu);
    dst_p->reserved4 = unpack_right_shift_u8(src_p[6], 0u, 0xffu);
    dst_p->tail_byte = unpack_right_shift_u8(src_p[7], 0u, 0xffu);

    return (0);
}

int can_lib_msg3_init(struct can_lib_msg3_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct can_lib_msg3_t));

    return 0;
}

uint8_t can_lib_msg3_mos_t_encode(double value)
{
    return (uint8_t)(value);
}

double can_lib_msg3_mos_t_decode(uint8_t value)
{
    return ((double)value);
}

bool can_lib_msg3_mos_t_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

bool can_lib_msg3_mos_t_is_in_phys_range(double value)
{
    return ((value >= 0.0) && (value <= 255.0));
}

uint8_t can_lib_msg3_cap_t_encode(double value)
{
    return (uint8_t)(value);
}

double can_lib_msg3_cap_t_decode(uint8_t value)
{
    return ((double)value);
}

bool can_lib_msg3_cap_t_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

bool can_lib_msg3_cap_t_is_in_phys_range(double value)
{
    return ((value >= 0.0) && (value <= 255.0));
}

uint8_t can_lib_msg3_motor_t_encode(double value)
{
    return (uint8_t)(value);
}

double can_lib_msg3_motor_t_decode(uint8_t value)
{
    return ((double)value);
}

bool can_lib_msg3_motor_t_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

bool can_lib_msg3_motor_t_is_in_phys_range(double value)
{
    return ((value >= 0.0) && (value <= 255.0));
}

uint8_t can_lib_msg3_reserved1_encode(double value)
{
    return (uint8_t)(value);
}

double can_lib_msg3_reserved1_decode(uint8_t value)
{
    return ((double)value);
}

bool can_lib_msg3_reserved1_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

bool can_lib_msg3_reserved1_is_in_phys_range(double value)
{
    return ((value >= 0.0) && (value <= 255.0));
}

uint8_t can_lib_msg3_reserved2_encode(double value)
{
    return (uint8_t)(value);
}

double can_lib_msg3_reserved2_decode(uint8_t value)
{
    return ((double)value);
}

bool can_lib_msg3_reserved2_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

bool can_lib_msg3_reserved2_is_in_phys_range(double value)
{
    return ((value >= 0.0) && (value <= 255.0));
}

uint8_t can_lib_msg3_reserved3_encode(double value)
{
    return (uint8_t)(value);
}

double can_lib_msg3_reserved3_decode(uint8_t value)
{
    return ((double)value);
}

bool can_lib_msg3_reserved3_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

bool can_lib_msg3_reserved3_is_in_phys_range(double value)
{
    return ((value >= 0.0) && (value <= 255.0));
}

uint8_t can_lib_msg3_reserved4_encode(double value)
{
    return (uint8_t)(value);
}

double can_lib_msg3_reserved4_decode(uint8_t value)
{
    return ((double)value);
}

bool can_lib_msg3_reserved4_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

bool can_lib_msg3_reserved4_is_in_phys_range(double value)
{
    return ((value >= 0.0) && (value <= 255.0));
}

uint8_t can_lib_msg3_tail_byte_encode(double value)
{
    return (uint8_t)(value);
}

double can_lib_msg3_tail_byte_decode(uint8_t value)
{
    return ((double)value);
}

bool can_lib_msg3_tail_byte_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

bool can_lib_msg3_tail_byte_is_in_phys_range(double value)
{
    return ((value >= 0.0) && (value <= 255.0));
}

int can_lib_thrust_pack(
    uint8_t *dst_p,
    const struct can_lib_thrust_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_left_shift_u8(src_p->b1, 0u, 0xffu);
    dst_p[1] |= pack_left_shift_u8(src_p->b2, 0u, 0xffu);
    dst_p[2] |= pack_left_shift_u8(src_p->b3, 0u, 0xffu);
    dst_p[3] |= pack_left_shift_u8(src_p->b4, 0u, 0xffu);
    dst_p[4] |= pack_left_shift_u8(src_p->b5, 0u, 0xffu);
    dst_p[5] |= pack_left_shift_u8(src_p->b6, 0u, 0xffu);
    dst_p[6] |= pack_left_shift_u8(src_p->b7, 0u, 0xffu);
    dst_p[7] |= pack_left_shift_u8(src_p->tail_byte, 0u, 0xffu);

    return (8);
}

int can_lib_thrust_unpack(
    struct can_lib_thrust_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->b1 = unpack_right_shift_u8(src_p[0], 0u, 0xffu);
    dst_p->b2 = unpack_right_shift_u8(src_p[1], 0u, 0xffu);
    dst_p->b3 = unpack_right_shift_u8(src_p[2], 0u, 0xffu);
    dst_p->b4 = unpack_right_shift_u8(src_p[3], 0u, 0xffu);
    dst_p->b5 = unpack_right_shift_u8(src_p[4], 0u, 0xffu);
    dst_p->b6 = unpack_right_shift_u8(src_p[5], 0u, 0xffu);
    dst_p->b7 = unpack_right_shift_u8(src_p[6], 0u, 0xffu);
    dst_p->tail_byte = unpack_right_shift_u8(src_p[7], 0u, 0xffu);

    return (0);
}

int can_lib_thrust_init(struct can_lib_thrust_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct can_lib_thrust_t));

    return 0;
}

uint8_t can_lib_thrust_b1_encode(double value)
{
    return (uint8_t)(value);
}

double can_lib_thrust_b1_decode(uint8_t value)
{
    return ((double)value);
}

bool can_lib_thrust_b1_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

bool can_lib_thrust_b1_is_in_phys_range(double value)
{
    return ((value >= 0.0) && (value <= 255.0));
}

uint8_t can_lib_thrust_b2_encode(double value)
{
    return (uint8_t)(value);
}

double can_lib_thrust_b2_decode(uint8_t value)
{
    return ((double)value);
}

bool can_lib_thrust_b2_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

bool can_lib_thrust_b2_is_in_phys_range(double value)
{
    return ((value >= 0.0) && (value <= 255.0));
}

uint8_t can_lib_thrust_b3_encode(double value)
{
    return (uint8_t)(value);
}

double can_lib_thrust_b3_decode(uint8_t value)
{
    return ((double)value);
}

bool can_lib_thrust_b3_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

bool can_lib_thrust_b3_is_in_phys_range(double value)
{
    return ((value >= 0.0) && (value <= 255.0));
}

uint8_t can_lib_thrust_b4_encode(double value)
{
    return (uint8_t)(value);
}

double can_lib_thrust_b4_decode(uint8_t value)
{
    return ((double)value);
}

bool can_lib_thrust_b4_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

bool can_lib_thrust_b4_is_in_phys_range(double value)
{
    return ((value >= 0.0) && (value <= 255.0));
}

uint8_t can_lib_thrust_b5_encode(double value)
{
    return (uint8_t)(value);
}

double can_lib_thrust_b5_decode(uint8_t value)
{
    return ((double)value);
}

bool can_lib_thrust_b5_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

bool can_lib_thrust_b5_is_in_phys_range(double value)
{
    return ((value >= 0.0) && (value <= 255.0));
}

uint8_t can_lib_thrust_b6_encode(double value)
{
    return (uint8_t)(value);
}

double can_lib_thrust_b6_decode(uint8_t value)
{
    return ((double)value);
}

bool can_lib_thrust_b6_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

bool can_lib_thrust_b6_is_in_phys_range(double value)
{
    return ((value >= 0.0) && (value <= 255.0));
}

uint8_t can_lib_thrust_b7_encode(double value)
{
    return (uint8_t)(value);
}

double can_lib_thrust_b7_decode(uint8_t value)
{
    return ((double)value);
}

bool can_lib_thrust_b7_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

bool can_lib_thrust_b7_is_in_phys_range(double value)
{
    return ((value >= 0.0) && (value <= 255.0));
}

uint8_t can_lib_thrust_tail_byte_encode(double value)
{
    return (uint8_t)(value);
}

double can_lib_thrust_tail_byte_decode(uint8_t value)
{
    return ((double)value);
}

bool can_lib_thrust_tail_byte_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

bool can_lib_thrust_tail_byte_is_in_phys_range(double value)
{
    return ((value >= 0.0) && (value <= 255.0));
}

int can_lib_bms_status_a_pack(
    uint8_t *dst_p,
    const struct can_lib_bms_status_a_t *src_p,
    size_t size)
{
    uint16_t pack_current;

    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_left_shift_u8(src_p->bms_state, 0u, 0x07u);
    dst_p[0] |= pack_left_shift_u16(src_p->bms_faults, 3u, 0xf8u);
    dst_p[1] |= pack_right_shift_u16(src_p->bms_faults, 5u, 0xffu);
    dst_p[2] |= pack_right_shift_u16(src_p->bms_faults, 13u, 0x03u);
    dst_p[2] |= pack_left_shift_u16(src_p->pack_voltage, 2u, 0xfcu);
    dst_p[3] |= pack_right_shift_u16(src_p->pack_voltage, 6u, 0xffu);
    dst_p[4] |= pack_right_shift_u16(src_p->pack_voltage, 14u, 0x03u);
    pack_current = (uint16_t)src_p->pack_current;
    dst_p[4] |= pack_left_shift_u16(pack_current, 2u, 0xfcu);
    dst_p[5] |= pack_right_shift_u16(pack_current, 6u, 0x0fu);
    dst_p[5] |= pack_left_shift_u16(src_p->balancing_mask, 4u, 0xf0u);
    dst_p[6] |= pack_right_shift_u16(src_p->balancing_mask, 4u, 0xffu);
    dst_p[7] |= pack_right_shift_u16(src_p->balancing_mask, 12u, 0x03u);

    return (8);
}

int can_lib_bms_status_a_unpack(
    struct can_lib_bms_status_a_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    uint16_t pack_current;

    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->bms_state = unpack_right_shift_u8(src_p[0], 0u, 0x07u);
    dst_p->bms_faults = unpack_right_shift_u16(src_p[0], 3u, 0xf8u);
    dst_p->bms_faults |= unpack_left_shift_u16(src_p[1], 5u, 0xffu);
    dst_p->bms_faults |= unpack_left_shift_u16(src_p[2], 13u, 0x03u);
    dst_p->pack_voltage = unpack_right_shift_u16(src_p[2], 2u, 0xfcu);
    dst_p->pack_voltage |= unpack_left_shift_u16(src_p[3], 6u, 0xffu);
    dst_p->pack_voltage |= unpack_left_shift_u16(src_p[4], 14u, 0x03u);
    pack_current = unpack_right_shift_u16(src_p[4], 2u, 0xfcu);
    pack_current |= unpack_left_shift_u16(src_p[5], 6u, 0x0fu);

    if ((pack_current & (1u << 9)) != 0u) {
        pack_current |= 0xfc00u;
    }

    dst_p->pack_current = (int16_t)pack_current;
    dst_p->balancing_mask = unpack_right_shift_u16(src_p[5], 4u, 0xf0u);
    dst_p->balancing_mask |= unpack_left_shift_u16(src_p[6], 4u, 0xffu);
    dst_p->balancing_mask |= unpack_left_shift_u16(src_p[7], 12u, 0x03u);

    return (0);
}

int can_lib_bms_status_a_init(struct can_lib_bms_status_a_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct can_lib_bms_status_a_t));

    return 0;
}

uint8_t can_lib_bms_status_a_bms_state_encode(double value)
{
    return (uint8_t)(value);
}

double can_lib_bms_status_a_bms_state_decode(uint8_t value)
{
    return ((double)value);
}

bool can_lib_bms_status_a_bms_state_is_in_range(uint8_t value)
{
    return (value <= 7u);
}

bool can_lib_bms_status_a_bms_state_is_in_phys_range(double value)
{
    (void)value;

    return (true);
}

uint16_t can_lib_bms_status_a_bms_faults_encode(double value)
{
    return (uint16_t)(value);
}

double can_lib_bms_status_a_bms_faults_decode(uint16_t value)
{
    return ((double)value);
}

bool can_lib_bms_status_a_bms_faults_is_in_range(uint16_t value)
{
    return (value <= 32767u);
}

bool can_lib_bms_status_a_bms_faults_is_in_phys_range(double value)
{
    (void)value;

    return (true);
}

uint16_t can_lib_bms_status_a_pack_voltage_encode(double value)
{
    return (uint16_t)(value);
}

double can_lib_bms_status_a_pack_voltage_decode(uint16_t value)
{
    return ((double)value);
}

bool can_lib_bms_status_a_pack_voltage_is_in_range(uint16_t value)
{
    return (value <= 700u);
}

bool can_lib_bms_status_a_pack_voltage_is_in_phys_range(double value)
{
    return ((value >= 0.0) && (value <= 700.0));
}

int16_t can_lib_bms_status_a_pack_current_encode(double value)
{
    return (int16_t)(value);
}

double can_lib_bms_status_a_pack_current_decode(int16_t value)
{
    return ((double)value);
}

bool can_lib_bms_status_a_pack_current_is_in_range(int16_t value)
{
    return ((value >= -511) && (value <= 511));
}

bool can_lib_bms_status_a_pack_current_is_in_phys_range(double value)
{
    return ((value >= -511.0) && (value <= 511.0));
}

uint16_t can_lib_bms_status_a_balancing_mask_encode(double value)
{
    return (uint16_t)(value);
}

double can_lib_bms_status_a_balancing_mask_decode(uint16_t value)
{
    return ((double)value);
}

bool can_lib_bms_status_a_balancing_mask_is_in_range(uint16_t value)
{
    return (value <= 16383u);
}

bool can_lib_bms_status_a_balancing_mask_is_in_phys_range(double value)
{
    (void)value;

    return (true);
}

int can_lib_bms_temp_metrics_a_pack(
    uint8_t *dst_p,
    const struct can_lib_bms_temp_metrics_a_t *src_p,
    size_t size)
{
    uint16_t max_cell_temp_ever;
    uint16_t max_current_cell_temp;
    uint16_t min_cell_temp_ever;
    uint16_t min_current_cell_temp;
    uint16_t temp_threshold_high;
    uint16_t temp_threshold_low;

    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    max_current_cell_temp = (uint16_t)src_p->max_current_cell_temp;
    dst_p[0] |= pack_left_shift_u16(max_current_cell_temp, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u16(max_current_cell_temp, 8u, 0x03u);
    min_current_cell_temp = (uint16_t)src_p->min_current_cell_temp;
    dst_p[1] |= pack_left_shift_u16(min_current_cell_temp, 2u, 0xfcu);
    dst_p[2] |= pack_right_shift_u16(min_current_cell_temp, 6u, 0x0fu);
    max_cell_temp_ever = (uint16_t)src_p->max_cell_temp_ever;
    dst_p[2] |= pack_left_shift_u16(max_cell_temp_ever, 4u, 0xf0u);
    dst_p[3] |= pack_right_shift_u16(max_cell_temp_ever, 4u, 0x3fu);
    min_cell_temp_ever = (uint16_t)src_p->min_cell_temp_ever;
    dst_p[3] |= pack_left_shift_u16(min_cell_temp_ever, 6u, 0xc0u);
    dst_p[4] |= pack_right_shift_u16(min_cell_temp_ever, 2u, 0xffu);
    temp_threshold_high = (uint16_t)src_p->temp_threshold_high;
    dst_p[5] |= pack_left_shift_u16(temp_threshold_high, 0u, 0xffu);
    dst_p[6] |= pack_right_shift_u16(temp_threshold_high, 8u, 0x03u);
    temp_threshold_low = (uint16_t)src_p->temp_threshold_low;
    dst_p[6] |= pack_left_shift_u16(temp_threshold_low, 2u, 0xfcu);
    dst_p[7] |= pack_right_shift_u16(temp_threshold_low, 6u, 0x0fu);

    return (8);
}

int can_lib_bms_temp_metrics_a_unpack(
    struct can_lib_bms_temp_metrics_a_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    uint16_t max_cell_temp_ever;
    uint16_t max_current_cell_temp;
    uint16_t min_cell_temp_ever;
    uint16_t min_current_cell_temp;
    uint16_t temp_threshold_high;
    uint16_t temp_threshold_low;

    if (size < 8u) {
        return (-EINVAL);
    }

    max_current_cell_temp = unpack_right_shift_u16(src_p[0], 0u, 0xffu);
    max_current_cell_temp |= unpack_left_shift_u16(src_p[1], 8u, 0x03u);

    if ((max_current_cell_temp & (1u << 9)) != 0u) {
        max_current_cell_temp |= 0xfc00u;
    }

    dst_p->max_current_cell_temp = (int16_t)max_current_cell_temp;
    min_current_cell_temp = unpack_right_shift_u16(src_p[1], 2u, 0xfcu);
    min_current_cell_temp |= unpack_left_shift_u16(src_p[2], 6u, 0x0fu);

    if ((min_current_cell_temp & (1u << 9)) != 0u) {
        min_current_cell_temp |= 0xfc00u;
    }

    dst_p->min_current_cell_temp = (int16_t)min_current_cell_temp;
    max_cell_temp_ever = unpack_right_shift_u16(src_p[2], 4u, 0xf0u);
    max_cell_temp_ever |= unpack_left_shift_u16(src_p[3], 4u, 0x3fu);

    if ((max_cell_temp_ever & (1u << 9)) != 0u) {
        max_cell_temp_ever |= 0xfc00u;
    }

    dst_p->max_cell_temp_ever = (int16_t)max_cell_temp_ever;
    min_cell_temp_ever = unpack_right_shift_u16(src_p[3], 6u, 0xc0u);
    min_cell_temp_ever |= unpack_left_shift_u16(src_p[4], 2u, 0xffu);

    if ((min_cell_temp_ever & (1u << 9)) != 0u) {
        min_cell_temp_ever |= 0xfc00u;
    }

    dst_p->min_cell_temp_ever = (int16_t)min_cell_temp_ever;
    temp_threshold_high = unpack_right_shift_u16(src_p[5], 0u, 0xffu);
    temp_threshold_high |= unpack_left_shift_u16(src_p[6], 8u, 0x03u);

    if ((temp_threshold_high & (1u << 9)) != 0u) {
        temp_threshold_high |= 0xfc00u;
    }

    dst_p->temp_threshold_high = (int16_t)temp_threshold_high;
    temp_threshold_low = unpack_right_shift_u16(src_p[6], 2u, 0xfcu);
    temp_threshold_low |= unpack_left_shift_u16(src_p[7], 6u, 0x0fu);

    if ((temp_threshold_low & (1u << 9)) != 0u) {
        temp_threshold_low |= 0xfc00u;
    }

    dst_p->temp_threshold_low = (int16_t)temp_threshold_low;

    return (0);
}

int can_lib_bms_temp_metrics_a_init(struct can_lib_bms_temp_metrics_a_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct can_lib_bms_temp_metrics_a_t));

    return 0;
}

int16_t can_lib_bms_temp_metrics_a_max_current_cell_temp_encode(double value)
{
    return (int16_t)(value);
}

double can_lib_bms_temp_metrics_a_max_current_cell_temp_decode(int16_t value)
{
    return ((double)value);
}

bool can_lib_bms_temp_metrics_a_max_current_cell_temp_is_in_range(int16_t value)
{
    return ((value >= -20) && (value <= 120));
}

bool can_lib_bms_temp_metrics_a_max_current_cell_temp_is_in_phys_range(double value)
{
    return ((value >= -20.0) && (value <= 120.0));
}

int16_t can_lib_bms_temp_metrics_a_min_current_cell_temp_encode(double value)
{
    return (int16_t)(value);
}

double can_lib_bms_temp_metrics_a_min_current_cell_temp_decode(int16_t value)
{
    return ((double)value);
}

bool can_lib_bms_temp_metrics_a_min_current_cell_temp_is_in_range(int16_t value)
{
    return ((value >= -20) && (value <= 120));
}

bool can_lib_bms_temp_metrics_a_min_current_cell_temp_is_in_phys_range(double value)
{
    return ((value >= -20.0) && (value <= 120.0));
}

int16_t can_lib_bms_temp_metrics_a_max_cell_temp_ever_encode(double value)
{
    return (int16_t)(value);
}

double can_lib_bms_temp_metrics_a_max_cell_temp_ever_decode(int16_t value)
{
    return ((double)value);
}

bool can_lib_bms_temp_metrics_a_max_cell_temp_ever_is_in_range(int16_t value)
{
    return ((value >= -20) && (value <= 120));
}

bool can_lib_bms_temp_metrics_a_max_cell_temp_ever_is_in_phys_range(double value)
{
    return ((value >= -20.0) && (value <= 120.0));
}

int16_t can_lib_bms_temp_metrics_a_min_cell_temp_ever_encode(double value)
{
    return (int16_t)(value);
}

double can_lib_bms_temp_metrics_a_min_cell_temp_ever_decode(int16_t value)
{
    return ((double)value);
}

bool can_lib_bms_temp_metrics_a_min_cell_temp_ever_is_in_range(int16_t value)
{
    return ((value >= -20) && (value <= 120));
}

bool can_lib_bms_temp_metrics_a_min_cell_temp_ever_is_in_phys_range(double value)
{
    return ((value >= -20.0) && (value <= 120.0));
}

int16_t can_lib_bms_temp_metrics_a_temp_threshold_high_encode(double value)
{
    return (int16_t)(value);
}

double can_lib_bms_temp_metrics_a_temp_threshold_high_decode(int16_t value)
{
    return ((double)value);
}

bool can_lib_bms_temp_metrics_a_temp_threshold_high_is_in_range(int16_t value)
{
    return ((value >= -20) && (value <= 120));
}

bool can_lib_bms_temp_metrics_a_temp_threshold_high_is_in_phys_range(double value)
{
    return ((value >= -20.0) && (value <= 120.0));
}

int16_t can_lib_bms_temp_metrics_a_temp_threshold_low_encode(double value)
{
    return (int16_t)(value);
}

double can_lib_bms_temp_metrics_a_temp_threshold_low_decode(int16_t value)
{
    return ((double)value);
}

bool can_lib_bms_temp_metrics_a_temp_threshold_low_is_in_range(int16_t value)
{
    return ((value >= -20) && (value <= 120));
}

bool can_lib_bms_temp_metrics_a_temp_threshold_low_is_in_phys_range(double value)
{
    return ((value >= -20.0) && (value <= 120.0));
}

int can_lib_bms_voltage_metrics_a_pack(
    uint8_t *dst_p,
    const struct can_lib_bms_voltage_metrics_a_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_left_shift_u16(src_p->max_cell_voltage, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u16(src_p->max_cell_voltage, 8u, 0x0fu);
    dst_p[1] |= pack_left_shift_u16(src_p->min_cell_voltage, 4u, 0xf0u);
    dst_p[2] |= pack_right_shift_u16(src_p->min_cell_voltage, 4u, 0xffu);
    dst_p[3] |= pack_left_shift_u16(src_p->cell_voltage_threshold_high, 0u, 0xffu);
    dst_p[4] |= pack_right_shift_u16(src_p->cell_voltage_threshold_high, 8u, 0x0fu);
    dst_p[4] |= pack_left_shift_u16(src_p->cell_voltage_threshold_low, 4u, 0xf0u);
    dst_p[5] |= pack_right_shift_u16(src_p->cell_voltage_threshold_low, 4u, 0xffu);
    dst_p[6] |= pack_left_shift_u16(src_p->charger_target_voltage, 0u, 0xffu);
    dst_p[7] |= pack_right_shift_u16(src_p->charger_target_voltage, 8u, 0x0fu);

    return (8);
}

int can_lib_bms_voltage_metrics_a_unpack(
    struct can_lib_bms_voltage_metrics_a_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->max_cell_voltage = unpack_right_shift_u16(src_p[0], 0u, 0xffu);
    dst_p->max_cell_voltage |= unpack_left_shift_u16(src_p[1], 8u, 0x0fu);
    dst_p->min_cell_voltage = unpack_right_shift_u16(src_p[1], 4u, 0xf0u);
    dst_p->min_cell_voltage |= unpack_left_shift_u16(src_p[2], 4u, 0xffu);
    dst_p->cell_voltage_threshold_high = unpack_right_shift_u16(src_p[3], 0u, 0xffu);
    dst_p->cell_voltage_threshold_high |= unpack_left_shift_u16(src_p[4], 8u, 0x0fu);
    dst_p->cell_voltage_threshold_low = unpack_right_shift_u16(src_p[4], 4u, 0xf0u);
    dst_p->cell_voltage_threshold_low |= unpack_left_shift_u16(src_p[5], 4u, 0xffu);
    dst_p->charger_target_voltage = unpack_right_shift_u16(src_p[6], 0u, 0xffu);
    dst_p->charger_target_voltage |= unpack_left_shift_u16(src_p[7], 8u, 0x0fu);

    return (0);
}

int can_lib_bms_voltage_metrics_a_init(struct can_lib_bms_voltage_metrics_a_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct can_lib_bms_voltage_metrics_a_t));

    return 0;
}

uint16_t can_lib_bms_voltage_metrics_a_max_cell_voltage_encode(double value)
{
    return (uint16_t)(value);
}

double can_lib_bms_voltage_metrics_a_max_cell_voltage_decode(uint16_t value)
{
    return ((double)value);
}

bool can_lib_bms_voltage_metrics_a_max_cell_voltage_is_in_range(uint16_t value)
{
    return (value <= 500u);
}

bool can_lib_bms_voltage_metrics_a_max_cell_voltage_is_in_phys_range(double value)
{
    return ((value >= 0.0) && (value <= 500.0));
}

uint16_t can_lib_bms_voltage_metrics_a_min_cell_voltage_encode(double value)
{
    return (uint16_t)(value);
}

double can_lib_bms_voltage_metrics_a_min_cell_voltage_decode(uint16_t value)
{
    return ((double)value);
}

bool can_lib_bms_voltage_metrics_a_min_cell_voltage_is_in_range(uint16_t value)
{
    return (value <= 500u);
}

bool can_lib_bms_voltage_metrics_a_min_cell_voltage_is_in_phys_range(double value)
{
    return ((value >= 0.0) && (value <= 500.0));
}

uint16_t can_lib_bms_voltage_metrics_a_cell_voltage_threshold_high_encode(double value)
{
    return (uint16_t)(value);
}

double can_lib_bms_voltage_metrics_a_cell_voltage_threshold_high_decode(uint16_t value)
{
    return ((double)value);
}

bool can_lib_bms_voltage_metrics_a_cell_voltage_threshold_high_is_in_range(uint16_t value)
{
    return (value <= 500u);
}

bool can_lib_bms_voltage_metrics_a_cell_voltage_threshold_high_is_in_phys_range(double value)
{
    return ((value >= 0.0) && (value <= 500.0));
}

uint16_t can_lib_bms_voltage_metrics_a_cell_voltage_threshold_low_encode(double value)
{
    return (uint16_t)(value);
}

double can_lib_bms_voltage_metrics_a_cell_voltage_threshold_low_decode(uint16_t value)
{
    return ((double)value);
}

bool can_lib_bms_voltage_metrics_a_cell_voltage_threshold_low_is_in_range(uint16_t value)
{
    return (value <= 500u);
}

bool can_lib_bms_voltage_metrics_a_cell_voltage_threshold_low_is_in_phys_range(double value)
{
    return ((value >= 0.0) && (value <= 500.0));
}

uint16_t can_lib_bms_voltage_metrics_a_charger_target_voltage_encode(double value)
{
    return (uint16_t)(value);
}

double can_lib_bms_voltage_metrics_a_charger_target_voltage_decode(uint16_t value)
{
    return ((double)value);
}

bool can_lib_bms_voltage_metrics_a_charger_target_voltage_is_in_range(uint16_t value)
{
    return (value <= 700u);
}

bool can_lib_bms_voltage_metrics_a_charger_target_voltage_is_in_phys_range(double value)
{
    return ((value >= 0.0) && (value <= 700.0));
}

int can_lib_cell_voltages_0_a_pack(
    uint8_t *dst_p,
    const struct can_lib_cell_voltages_0_a_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_left_shift_u16(src_p->cell_1, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u16(src_p->cell_1, 8u, 0x0fu);
    dst_p[1] |= pack_left_shift_u16(src_p->cell_2, 4u, 0xf0u);
    dst_p[2] |= pack_right_shift_u16(src_p->cell_2, 4u, 0xffu);
    dst_p[3] |= pack_left_shift_u16(src_p->cell_3, 0u, 0xffu);
    dst_p[4] |= pack_right_shift_u16(src_p->cell_3, 8u, 0x0fu);
    dst_p[4] |= pack_left_shift_u16(src_p->cell_4, 4u, 0xf0u);
    dst_p[5] |= pack_right_shift_u16(src_p->cell_4, 4u, 0xffu);
    dst_p[6] |= pack_left_shift_u16(src_p->cell_5, 0u, 0xffu);
    dst_p[7] |= pack_right_shift_u16(src_p->cell_5, 8u, 0x0fu);

    return (8);
}

int can_lib_cell_voltages_0_a_unpack(
    struct can_lib_cell_voltages_0_a_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->cell_1 = unpack_right_shift_u16(src_p[0], 0u, 0xffu);
    dst_p->cell_1 |= unpack_left_shift_u16(src_p[1], 8u, 0x0fu);
    dst_p->cell_2 = unpack_right_shift_u16(src_p[1], 4u, 0xf0u);
    dst_p->cell_2 |= unpack_left_shift_u16(src_p[2], 4u, 0xffu);
    dst_p->cell_3 = unpack_right_shift_u16(src_p[3], 0u, 0xffu);
    dst_p->cell_3 |= unpack_left_shift_u16(src_p[4], 8u, 0x0fu);
    dst_p->cell_4 = unpack_right_shift_u16(src_p[4], 4u, 0xf0u);
    dst_p->cell_4 |= unpack_left_shift_u16(src_p[5], 4u, 0xffu);
    dst_p->cell_5 = unpack_right_shift_u16(src_p[6], 0u, 0xffu);
    dst_p->cell_5 |= unpack_left_shift_u16(src_p[7], 8u, 0x0fu);

    return (0);
}

int can_lib_cell_voltages_0_a_init(struct can_lib_cell_voltages_0_a_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct can_lib_cell_voltages_0_a_t));

    return 0;
}

uint16_t can_lib_cell_voltages_0_a_cell_1_encode(double value)
{
    return (uint16_t)(value);
}

double can_lib_cell_voltages_0_a_cell_1_decode(uint16_t value)
{
    return ((double)value);
}

bool can_lib_cell_voltages_0_a_cell_1_is_in_range(uint16_t value)
{
    return (value <= 500u);
}

bool can_lib_cell_voltages_0_a_cell_1_is_in_phys_range(double value)
{
    return ((value >= 0.0) && (value <= 500.0));
}

uint16_t can_lib_cell_voltages_0_a_cell_2_encode(double value)
{
    return (uint16_t)(value);
}

double can_lib_cell_voltages_0_a_cell_2_decode(uint16_t value)
{
    return ((double)value);
}

bool can_lib_cell_voltages_0_a_cell_2_is_in_range(uint16_t value)
{
    return (value <= 500u);
}

bool can_lib_cell_voltages_0_a_cell_2_is_in_phys_range(double value)
{
    return ((value >= 0.0) && (value <= 500.0));
}

uint16_t can_lib_cell_voltages_0_a_cell_3_encode(double value)
{
    return (uint16_t)(value);
}

double can_lib_cell_voltages_0_a_cell_3_decode(uint16_t value)
{
    return ((double)value);
}

bool can_lib_cell_voltages_0_a_cell_3_is_in_range(uint16_t value)
{
    return (value <= 500u);
}

bool can_lib_cell_voltages_0_a_cell_3_is_in_phys_range(double value)
{
    return ((value >= 0.0) && (value <= 500.0));
}

uint16_t can_lib_cell_voltages_0_a_cell_4_encode(double value)
{
    return (uint16_t)(value);
}

double can_lib_cell_voltages_0_a_cell_4_decode(uint16_t value)
{
    return ((double)value);
}

bool can_lib_cell_voltages_0_a_cell_4_is_in_range(uint16_t value)
{
    return (value <= 500u);
}

bool can_lib_cell_voltages_0_a_cell_4_is_in_phys_range(double value)
{
    return ((value >= 0.0) && (value <= 500.0));
}

uint16_t can_lib_cell_voltages_0_a_cell_5_encode(double value)
{
    return (uint16_t)(value);
}

double can_lib_cell_voltages_0_a_cell_5_decode(uint16_t value)
{
    return ((double)value);
}

bool can_lib_cell_voltages_0_a_cell_5_is_in_range(uint16_t value)
{
    return (value <= 500u);
}

bool can_lib_cell_voltages_0_a_cell_5_is_in_phys_range(double value)
{
    return ((value >= 0.0) && (value <= 500.0));
}

int can_lib_cell_voltages_1_a_pack(
    uint8_t *dst_p,
    const struct can_lib_cell_voltages_1_a_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_left_shift_u16(src_p->cell_6, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u16(src_p->cell_6, 8u, 0x0fu);
    dst_p[1] |= pack_left_shift_u16(src_p->cell_7, 4u, 0xf0u);
    dst_p[2] |= pack_right_shift_u16(src_p->cell_7, 4u, 0xffu);
    dst_p[3] |= pack_left_shift_u16(src_p->cell_8, 0u, 0xffu);
    dst_p[4] |= pack_right_shift_u16(src_p->cell_8, 8u, 0x0fu);
    dst_p[4] |= pack_left_shift_u16(src_p->cell_9, 4u, 0xf0u);
    dst_p[5] |= pack_right_shift_u16(src_p->cell_9, 4u, 0xffu);
    dst_p[6] |= pack_left_shift_u16(src_p->cell_10, 0u, 0xffu);
    dst_p[7] |= pack_right_shift_u16(src_p->cell_10, 8u, 0x0fu);

    return (8);
}

int can_lib_cell_voltages_1_a_unpack(
    struct can_lib_cell_voltages_1_a_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->cell_6 = unpack_right_shift_u16(src_p[0], 0u, 0xffu);
    dst_p->cell_6 |= unpack_left_shift_u16(src_p[1], 8u, 0x0fu);
    dst_p->cell_7 = unpack_right_shift_u16(src_p[1], 4u, 0xf0u);
    dst_p->cell_7 |= unpack_left_shift_u16(src_p[2], 4u, 0xffu);
    dst_p->cell_8 = unpack_right_shift_u16(src_p[3], 0u, 0xffu);
    dst_p->cell_8 |= unpack_left_shift_u16(src_p[4], 8u, 0x0fu);
    dst_p->cell_9 = unpack_right_shift_u16(src_p[4], 4u, 0xf0u);
    dst_p->cell_9 |= unpack_left_shift_u16(src_p[5], 4u, 0xffu);
    dst_p->cell_10 = unpack_right_shift_u16(src_p[6], 0u, 0xffu);
    dst_p->cell_10 |= unpack_left_shift_u16(src_p[7], 8u, 0x0fu);

    return (0);
}

int can_lib_cell_voltages_1_a_init(struct can_lib_cell_voltages_1_a_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct can_lib_cell_voltages_1_a_t));

    return 0;
}

uint16_t can_lib_cell_voltages_1_a_cell_6_encode(double value)
{
    return (uint16_t)(value);
}

double can_lib_cell_voltages_1_a_cell_6_decode(uint16_t value)
{
    return ((double)value);
}

bool can_lib_cell_voltages_1_a_cell_6_is_in_range(uint16_t value)
{
    return (value <= 500u);
}

bool can_lib_cell_voltages_1_a_cell_6_is_in_phys_range(double value)
{
    return ((value >= 0.0) && (value <= 500.0));
}

uint16_t can_lib_cell_voltages_1_a_cell_7_encode(double value)
{
    return (uint16_t)(value);
}

double can_lib_cell_voltages_1_a_cell_7_decode(uint16_t value)
{
    return ((double)value);
}

bool can_lib_cell_voltages_1_a_cell_7_is_in_range(uint16_t value)
{
    return (value <= 500u);
}

bool can_lib_cell_voltages_1_a_cell_7_is_in_phys_range(double value)
{
    return ((value >= 0.0) && (value <= 500.0));
}

uint16_t can_lib_cell_voltages_1_a_cell_8_encode(double value)
{
    return (uint16_t)(value);
}

double can_lib_cell_voltages_1_a_cell_8_decode(uint16_t value)
{
    return ((double)value);
}

bool can_lib_cell_voltages_1_a_cell_8_is_in_range(uint16_t value)
{
    return (value <= 500u);
}

bool can_lib_cell_voltages_1_a_cell_8_is_in_phys_range(double value)
{
    return ((value >= 0.0) && (value <= 500.0));
}

uint16_t can_lib_cell_voltages_1_a_cell_9_encode(double value)
{
    return (uint16_t)(value);
}

double can_lib_cell_voltages_1_a_cell_9_decode(uint16_t value)
{
    return ((double)value);
}

bool can_lib_cell_voltages_1_a_cell_9_is_in_range(uint16_t value)
{
    return (value <= 500u);
}

bool can_lib_cell_voltages_1_a_cell_9_is_in_phys_range(double value)
{
    return ((value >= 0.0) && (value <= 500.0));
}

uint16_t can_lib_cell_voltages_1_a_cell_10_encode(double value)
{
    return (uint16_t)(value);
}

double can_lib_cell_voltages_1_a_cell_10_decode(uint16_t value)
{
    return ((double)value);
}

bool can_lib_cell_voltages_1_a_cell_10_is_in_range(uint16_t value)
{
    return (value <= 500u);
}

bool can_lib_cell_voltages_1_a_cell_10_is_in_phys_range(double value)
{
    return ((value >= 0.0) && (value <= 500.0));
}

int can_lib_cell_voltages_2_a_pack(
    uint8_t *dst_p,
    const struct can_lib_cell_voltages_2_a_t *src_p,
    size_t size)
{
    if (size < 6u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 6);

    dst_p[0] |= pack_left_shift_u16(src_p->cell_11, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u16(src_p->cell_11, 8u, 0x0fu);
    dst_p[1] |= pack_left_shift_u16(src_p->cell_12, 4u, 0xf0u);
    dst_p[2] |= pack_right_shift_u16(src_p->cell_12, 4u, 0xffu);
    dst_p[3] |= pack_left_shift_u16(src_p->cell_13, 0u, 0xffu);
    dst_p[4] |= pack_right_shift_u16(src_p->cell_13, 8u, 0x0fu);
    dst_p[4] |= pack_left_shift_u16(src_p->cell_14, 4u, 0xf0u);
    dst_p[5] |= pack_right_shift_u16(src_p->cell_14, 4u, 0xffu);

    return (6);
}

int can_lib_cell_voltages_2_a_unpack(
    struct can_lib_cell_voltages_2_a_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 6u) {
        return (-EINVAL);
    }

    dst_p->cell_11 = unpack_right_shift_u16(src_p[0], 0u, 0xffu);
    dst_p->cell_11 |= unpack_left_shift_u16(src_p[1], 8u, 0x0fu);
    dst_p->cell_12 = unpack_right_shift_u16(src_p[1], 4u, 0xf0u);
    dst_p->cell_12 |= unpack_left_shift_u16(src_p[2], 4u, 0xffu);
    dst_p->cell_13 = unpack_right_shift_u16(src_p[3], 0u, 0xffu);
    dst_p->cell_13 |= unpack_left_shift_u16(src_p[4], 8u, 0x0fu);
    dst_p->cell_14 = unpack_right_shift_u16(src_p[4], 4u, 0xf0u);
    dst_p->cell_14 |= unpack_left_shift_u16(src_p[5], 4u, 0xffu);

    return (0);
}

int can_lib_cell_voltages_2_a_init(struct can_lib_cell_voltages_2_a_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct can_lib_cell_voltages_2_a_t));

    return 0;
}

uint16_t can_lib_cell_voltages_2_a_cell_11_encode(double value)
{
    return (uint16_t)(value);
}

double can_lib_cell_voltages_2_a_cell_11_decode(uint16_t value)
{
    return ((double)value);
}

bool can_lib_cell_voltages_2_a_cell_11_is_in_range(uint16_t value)
{
    return (value <= 500u);
}

bool can_lib_cell_voltages_2_a_cell_11_is_in_phys_range(double value)
{
    return ((value >= 0.0) && (value <= 500.0));
}

uint16_t can_lib_cell_voltages_2_a_cell_12_encode(double value)
{
    return (uint16_t)(value);
}

double can_lib_cell_voltages_2_a_cell_12_decode(uint16_t value)
{
    return ((double)value);
}

bool can_lib_cell_voltages_2_a_cell_12_is_in_range(uint16_t value)
{
    return (value <= 500u);
}

bool can_lib_cell_voltages_2_a_cell_12_is_in_phys_range(double value)
{
    return ((value >= 0.0) && (value <= 500.0));
}

uint16_t can_lib_cell_voltages_2_a_cell_13_encode(double value)
{
    return (uint16_t)(value);
}

double can_lib_cell_voltages_2_a_cell_13_decode(uint16_t value)
{
    return ((double)value);
}

bool can_lib_cell_voltages_2_a_cell_13_is_in_range(uint16_t value)
{
    return (value <= 500u);
}

bool can_lib_cell_voltages_2_a_cell_13_is_in_phys_range(double value)
{
    return ((value >= 0.0) && (value <= 500.0));
}

uint16_t can_lib_cell_voltages_2_a_cell_14_encode(double value)
{
    return (uint16_t)(value);
}

double can_lib_cell_voltages_2_a_cell_14_decode(uint16_t value)
{
    return ((double)value);
}

bool can_lib_cell_voltages_2_a_cell_14_is_in_range(uint16_t value)
{
    return (value <= 500u);
}

bool can_lib_cell_voltages_2_a_cell_14_is_in_phys_range(double value)
{
    return ((value >= 0.0) && (value <= 500.0));
}

int can_lib_thermistors_0_a_pack(
    uint8_t *dst_p,
    const struct can_lib_thermistors_0_a_t *src_p,
    size_t size)
{
    uint16_t thermistor_1;
    uint16_t thermistor_2;
    uint16_t thermistor_3;
    uint16_t thermistor_4;
    uint16_t thermistor_5;
    uint16_t thermistor_6;

    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    thermistor_1 = (uint16_t)src_p->thermistor_1;
    dst_p[0] |= pack_left_shift_u16(thermistor_1, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u16(thermistor_1, 8u, 0x03u);
    thermistor_2 = (uint16_t)src_p->thermistor_2;
    dst_p[1] |= pack_left_shift_u16(thermistor_2, 2u, 0xfcu);
    dst_p[2] |= pack_right_shift_u16(thermistor_2, 6u, 0x0fu);
    thermistor_3 = (uint16_t)src_p->thermistor_3;
    dst_p[2] |= pack_left_shift_u16(thermistor_3, 4u, 0xf0u);
    dst_p[3] |= pack_right_shift_u16(thermistor_3, 4u, 0x3fu);
    thermistor_4 = (uint16_t)src_p->thermistor_4;
    dst_p[3] |= pack_left_shift_u16(thermistor_4, 6u, 0xc0u);
    dst_p[4] |= pack_right_shift_u16(thermistor_4, 2u, 0xffu);
    thermistor_5 = (uint16_t)src_p->thermistor_5;
    dst_p[5] |= pack_left_shift_u16(thermistor_5, 0u, 0xffu);
    dst_p[6] |= pack_right_shift_u16(thermistor_5, 8u, 0x03u);
    thermistor_6 = (uint16_t)src_p->thermistor_6;
    dst_p[6] |= pack_left_shift_u16(thermistor_6, 2u, 0xfcu);
    dst_p[7] |= pack_right_shift_u16(thermistor_6, 6u, 0x0fu);

    return (8);
}

int can_lib_thermistors_0_a_unpack(
    struct can_lib_thermistors_0_a_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    uint16_t thermistor_1;
    uint16_t thermistor_2;
    uint16_t thermistor_3;
    uint16_t thermistor_4;
    uint16_t thermistor_5;
    uint16_t thermistor_6;

    if (size < 8u) {
        return (-EINVAL);
    }

    thermistor_1 = unpack_right_shift_u16(src_p[0], 0u, 0xffu);
    thermistor_1 |= unpack_left_shift_u16(src_p[1], 8u, 0x03u);

    if ((thermistor_1 & (1u << 9)) != 0u) {
        thermistor_1 |= 0xfc00u;
    }

    dst_p->thermistor_1 = (int16_t)thermistor_1;
    thermistor_2 = unpack_right_shift_u16(src_p[1], 2u, 0xfcu);
    thermistor_2 |= unpack_left_shift_u16(src_p[2], 6u, 0x0fu);

    if ((thermistor_2 & (1u << 9)) != 0u) {
        thermistor_2 |= 0xfc00u;
    }

    dst_p->thermistor_2 = (int16_t)thermistor_2;
    thermistor_3 = unpack_right_shift_u16(src_p[2], 4u, 0xf0u);
    thermistor_3 |= unpack_left_shift_u16(src_p[3], 4u, 0x3fu);

    if ((thermistor_3 & (1u << 9)) != 0u) {
        thermistor_3 |= 0xfc00u;
    }

    dst_p->thermistor_3 = (int16_t)thermistor_3;
    thermistor_4 = unpack_right_shift_u16(src_p[3], 6u, 0xc0u);
    thermistor_4 |= unpack_left_shift_u16(src_p[4], 2u, 0xffu);

    if ((thermistor_4 & (1u << 9)) != 0u) {
        thermistor_4 |= 0xfc00u;
    }

    dst_p->thermistor_4 = (int16_t)thermistor_4;
    thermistor_5 = unpack_right_shift_u16(src_p[5], 0u, 0xffu);
    thermistor_5 |= unpack_left_shift_u16(src_p[6], 8u, 0x03u);

    if ((thermistor_5 & (1u << 9)) != 0u) {
        thermistor_5 |= 0xfc00u;
    }

    dst_p->thermistor_5 = (int16_t)thermistor_5;
    thermistor_6 = unpack_right_shift_u16(src_p[6], 2u, 0xfcu);
    thermistor_6 |= unpack_left_shift_u16(src_p[7], 6u, 0x0fu);

    if ((thermistor_6 & (1u << 9)) != 0u) {
        thermistor_6 |= 0xfc00u;
    }

    dst_p->thermistor_6 = (int16_t)thermistor_6;

    return (0);
}

int can_lib_thermistors_0_a_init(struct can_lib_thermistors_0_a_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct can_lib_thermistors_0_a_t));

    return 0;
}

int16_t can_lib_thermistors_0_a_thermistor_1_encode(double value)
{
    return (int16_t)(value);
}

double can_lib_thermistors_0_a_thermistor_1_decode(int16_t value)
{
    return ((double)value);
}

bool can_lib_thermistors_0_a_thermistor_1_is_in_range(int16_t value)
{
    return ((value >= -20) && (value <= 120));
}

bool can_lib_thermistors_0_a_thermistor_1_is_in_phys_range(double value)
{
    return ((value >= -20.0) && (value <= 120.0));
}

int16_t can_lib_thermistors_0_a_thermistor_2_encode(double value)
{
    return (int16_t)(value);
}

double can_lib_thermistors_0_a_thermistor_2_decode(int16_t value)
{
    return ((double)value);
}

bool can_lib_thermistors_0_a_thermistor_2_is_in_range(int16_t value)
{
    return ((value >= -20) && (value <= 120));
}

bool can_lib_thermistors_0_a_thermistor_2_is_in_phys_range(double value)
{
    return ((value >= -20.0) && (value <= 120.0));
}

int16_t can_lib_thermistors_0_a_thermistor_3_encode(double value)
{
    return (int16_t)(value);
}

double can_lib_thermistors_0_a_thermistor_3_decode(int16_t value)
{
    return ((double)value);
}

bool can_lib_thermistors_0_a_thermistor_3_is_in_range(int16_t value)
{
    return ((value >= -20) && (value <= 120));
}

bool can_lib_thermistors_0_a_thermistor_3_is_in_phys_range(double value)
{
    return ((value >= -20.0) && (value <= 120.0));
}

int16_t can_lib_thermistors_0_a_thermistor_4_encode(double value)
{
    return (int16_t)(value);
}

double can_lib_thermistors_0_a_thermistor_4_decode(int16_t value)
{
    return ((double)value);
}

bool can_lib_thermistors_0_a_thermistor_4_is_in_range(int16_t value)
{
    return ((value >= -20) && (value <= 120));
}

bool can_lib_thermistors_0_a_thermistor_4_is_in_phys_range(double value)
{
    return ((value >= -20.0) && (value <= 120.0));
}

int16_t can_lib_thermistors_0_a_thermistor_5_encode(double value)
{
    return (int16_t)(value);
}

double can_lib_thermistors_0_a_thermistor_5_decode(int16_t value)
{
    return ((double)value);
}

bool can_lib_thermistors_0_a_thermistor_5_is_in_range(int16_t value)
{
    return ((value >= -20) && (value <= 120));
}

bool can_lib_thermistors_0_a_thermistor_5_is_in_phys_range(double value)
{
    return ((value >= -20.0) && (value <= 120.0));
}

int16_t can_lib_thermistors_0_a_thermistor_6_encode(double value)
{
    return (int16_t)(value);
}

double can_lib_thermistors_0_a_thermistor_6_decode(int16_t value)
{
    return ((double)value);
}

bool can_lib_thermistors_0_a_thermistor_6_is_in_range(int16_t value)
{
    return ((value >= -20) && (value <= 120));
}

bool can_lib_thermistors_0_a_thermistor_6_is_in_phys_range(double value)
{
    return ((value >= -20.0) && (value <= 120.0));
}

int can_lib_thermistors_1_a_pack(
    uint8_t *dst_p,
    const struct can_lib_thermistors_1_a_t *src_p,
    size_t size)
{
    uint16_t thermistor_10;
    uint16_t thermistor_11;
    uint16_t thermistor_12;
    uint16_t thermistor_7;
    uint16_t thermistor_8;
    uint16_t thermistor_9;

    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    thermistor_7 = (uint16_t)src_p->thermistor_7;
    dst_p[0] |= pack_left_shift_u16(thermistor_7, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u16(thermistor_7, 8u, 0x03u);
    thermistor_8 = (uint16_t)src_p->thermistor_8;
    dst_p[1] |= pack_left_shift_u16(thermistor_8, 2u, 0xfcu);
    dst_p[2] |= pack_right_shift_u16(thermistor_8, 6u, 0x0fu);
    thermistor_9 = (uint16_t)src_p->thermistor_9;
    dst_p[2] |= pack_left_shift_u16(thermistor_9, 4u, 0xf0u);
    dst_p[3] |= pack_right_shift_u16(thermistor_9, 4u, 0x3fu);
    thermistor_10 = (uint16_t)src_p->thermistor_10;
    dst_p[3] |= pack_left_shift_u16(thermistor_10, 6u, 0xc0u);
    dst_p[4] |= pack_right_shift_u16(thermistor_10, 2u, 0xffu);
    thermistor_11 = (uint16_t)src_p->thermistor_11;
    dst_p[5] |= pack_left_shift_u16(thermistor_11, 0u, 0xffu);
    dst_p[6] |= pack_right_shift_u16(thermistor_11, 8u, 0x03u);
    thermistor_12 = (uint16_t)src_p->thermistor_12;
    dst_p[6] |= pack_left_shift_u16(thermistor_12, 2u, 0xfcu);
    dst_p[7] |= pack_right_shift_u16(thermistor_12, 6u, 0x0fu);

    return (8);
}

int can_lib_thermistors_1_a_unpack(
    struct can_lib_thermistors_1_a_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    uint16_t thermistor_10;
    uint16_t thermistor_11;
    uint16_t thermistor_12;
    uint16_t thermistor_7;
    uint16_t thermistor_8;
    uint16_t thermistor_9;

    if (size < 8u) {
        return (-EINVAL);
    }

    thermistor_7 = unpack_right_shift_u16(src_p[0], 0u, 0xffu);
    thermistor_7 |= unpack_left_shift_u16(src_p[1], 8u, 0x03u);

    if ((thermistor_7 & (1u << 9)) != 0u) {
        thermistor_7 |= 0xfc00u;
    }

    dst_p->thermistor_7 = (int16_t)thermistor_7;
    thermistor_8 = unpack_right_shift_u16(src_p[1], 2u, 0xfcu);
    thermistor_8 |= unpack_left_shift_u16(src_p[2], 6u, 0x0fu);

    if ((thermistor_8 & (1u << 9)) != 0u) {
        thermistor_8 |= 0xfc00u;
    }

    dst_p->thermistor_8 = (int16_t)thermistor_8;
    thermistor_9 = unpack_right_shift_u16(src_p[2], 4u, 0xf0u);
    thermistor_9 |= unpack_left_shift_u16(src_p[3], 4u, 0x3fu);

    if ((thermistor_9 & (1u << 9)) != 0u) {
        thermistor_9 |= 0xfc00u;
    }

    dst_p->thermistor_9 = (int16_t)thermistor_9;
    thermistor_10 = unpack_right_shift_u16(src_p[3], 6u, 0xc0u);
    thermistor_10 |= unpack_left_shift_u16(src_p[4], 2u, 0xffu);

    if ((thermistor_10 & (1u << 9)) != 0u) {
        thermistor_10 |= 0xfc00u;
    }

    dst_p->thermistor_10 = (int16_t)thermistor_10;
    thermistor_11 = unpack_right_shift_u16(src_p[5], 0u, 0xffu);
    thermistor_11 |= unpack_left_shift_u16(src_p[6], 8u, 0x03u);

    if ((thermistor_11 & (1u << 9)) != 0u) {
        thermistor_11 |= 0xfc00u;
    }

    dst_p->thermistor_11 = (int16_t)thermistor_11;
    thermistor_12 = unpack_right_shift_u16(src_p[6], 2u, 0xfcu);
    thermistor_12 |= unpack_left_shift_u16(src_p[7], 6u, 0x0fu);

    if ((thermistor_12 & (1u << 9)) != 0u) {
        thermistor_12 |= 0xfc00u;
    }

    dst_p->thermistor_12 = (int16_t)thermistor_12;

    return (0);
}

int can_lib_thermistors_1_a_init(struct can_lib_thermistors_1_a_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct can_lib_thermistors_1_a_t));

    return 0;
}

int16_t can_lib_thermistors_1_a_thermistor_7_encode(double value)
{
    return (int16_t)(value);
}

double can_lib_thermistors_1_a_thermistor_7_decode(int16_t value)
{
    return ((double)value);
}

bool can_lib_thermistors_1_a_thermistor_7_is_in_range(int16_t value)
{
    return ((value >= -20) && (value <= 120));
}

bool can_lib_thermistors_1_a_thermistor_7_is_in_phys_range(double value)
{
    return ((value >= -20.0) && (value <= 120.0));
}

int16_t can_lib_thermistors_1_a_thermistor_8_encode(double value)
{
    return (int16_t)(value);
}

double can_lib_thermistors_1_a_thermistor_8_decode(int16_t value)
{
    return ((double)value);
}

bool can_lib_thermistors_1_a_thermistor_8_is_in_range(int16_t value)
{
    return ((value >= -20) && (value <= 120));
}

bool can_lib_thermistors_1_a_thermistor_8_is_in_phys_range(double value)
{
    return ((value >= -20.0) && (value <= 120.0));
}

int16_t can_lib_thermistors_1_a_thermistor_9_encode(double value)
{
    return (int16_t)(value);
}

double can_lib_thermistors_1_a_thermistor_9_decode(int16_t value)
{
    return ((double)value);
}

bool can_lib_thermistors_1_a_thermistor_9_is_in_range(int16_t value)
{
    return ((value >= -20) && (value <= 120));
}

bool can_lib_thermistors_1_a_thermistor_9_is_in_phys_range(double value)
{
    return ((value >= -20.0) && (value <= 120.0));
}

int16_t can_lib_thermistors_1_a_thermistor_10_encode(double value)
{
    return (int16_t)(value);
}

double can_lib_thermistors_1_a_thermistor_10_decode(int16_t value)
{
    return ((double)value);
}

bool can_lib_thermistors_1_a_thermistor_10_is_in_range(int16_t value)
{
    return ((value >= -20) && (value <= 120));
}

bool can_lib_thermistors_1_a_thermistor_10_is_in_phys_range(double value)
{
    return ((value >= -20.0) && (value <= 120.0));
}

int16_t can_lib_thermistors_1_a_thermistor_11_encode(double value)
{
    return (int16_t)(value);
}

double can_lib_thermistors_1_a_thermistor_11_decode(int16_t value)
{
    return ((double)value);
}

bool can_lib_thermistors_1_a_thermistor_11_is_in_range(int16_t value)
{
    return ((value >= -20) && (value <= 120));
}

bool can_lib_thermistors_1_a_thermistor_11_is_in_phys_range(double value)
{
    return ((value >= -20.0) && (value <= 120.0));
}

int16_t can_lib_thermistors_1_a_thermistor_12_encode(double value)
{
    return (int16_t)(value);
}

double can_lib_thermistors_1_a_thermistor_12_decode(int16_t value)
{
    return ((double)value);
}

bool can_lib_thermistors_1_a_thermistor_12_is_in_range(int16_t value)
{
    return ((value >= -20) && (value <= 120));
}

bool can_lib_thermistors_1_a_thermistor_12_is_in_phys_range(double value)
{
    return ((value >= -20.0) && (value <= 120.0));
}

int can_lib_thermistors_2_a_pack(
    uint8_t *dst_p,
    const struct can_lib_thermistors_2_a_t *src_p,
    size_t size)
{
    uint16_t thermistor_13;
    uint16_t thermistor_14;
    uint16_t thermistor_15;
    uint16_t thermistor_16;
    uint16_t thermistor_17;
    uint16_t thermistor_18;

    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    thermistor_13 = (uint16_t)src_p->thermistor_13;
    dst_p[0] |= pack_left_shift_u16(thermistor_13, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u16(thermistor_13, 8u, 0x03u);
    thermistor_14 = (uint16_t)src_p->thermistor_14;
    dst_p[1] |= pack_left_shift_u16(thermistor_14, 2u, 0xfcu);
    dst_p[2] |= pack_right_shift_u16(thermistor_14, 6u, 0x0fu);
    thermistor_15 = (uint16_t)src_p->thermistor_15;
    dst_p[2] |= pack_left_shift_u16(thermistor_15, 4u, 0xf0u);
    dst_p[3] |= pack_right_shift_u16(thermistor_15, 4u, 0x3fu);
    thermistor_16 = (uint16_t)src_p->thermistor_16;
    dst_p[3] |= pack_left_shift_u16(thermistor_16, 6u, 0xc0u);
    dst_p[4] |= pack_right_shift_u16(thermistor_16, 2u, 0xffu);
    thermistor_17 = (uint16_t)src_p->thermistor_17;
    dst_p[5] |= pack_left_shift_u16(thermistor_17, 0u, 0xffu);
    dst_p[6] |= pack_right_shift_u16(thermistor_17, 8u, 0x03u);
    thermistor_18 = (uint16_t)src_p->thermistor_18;
    dst_p[6] |= pack_left_shift_u16(thermistor_18, 2u, 0xfcu);
    dst_p[7] |= pack_right_shift_u16(thermistor_18, 6u, 0x0fu);

    return (8);
}

int can_lib_thermistors_2_a_unpack(
    struct can_lib_thermistors_2_a_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    uint16_t thermistor_13;
    uint16_t thermistor_14;
    uint16_t thermistor_15;
    uint16_t thermistor_16;
    uint16_t thermistor_17;
    uint16_t thermistor_18;

    if (size < 8u) {
        return (-EINVAL);
    }

    thermistor_13 = unpack_right_shift_u16(src_p[0], 0u, 0xffu);
    thermistor_13 |= unpack_left_shift_u16(src_p[1], 8u, 0x03u);

    if ((thermistor_13 & (1u << 9)) != 0u) {
        thermistor_13 |= 0xfc00u;
    }

    dst_p->thermistor_13 = (int16_t)thermistor_13;
    thermistor_14 = unpack_right_shift_u16(src_p[1], 2u, 0xfcu);
    thermistor_14 |= unpack_left_shift_u16(src_p[2], 6u, 0x0fu);

    if ((thermistor_14 & (1u << 9)) != 0u) {
        thermistor_14 |= 0xfc00u;
    }

    dst_p->thermistor_14 = (int16_t)thermistor_14;
    thermistor_15 = unpack_right_shift_u16(src_p[2], 4u, 0xf0u);
    thermistor_15 |= unpack_left_shift_u16(src_p[3], 4u, 0x3fu);

    if ((thermistor_15 & (1u << 9)) != 0u) {
        thermistor_15 |= 0xfc00u;
    }

    dst_p->thermistor_15 = (int16_t)thermistor_15;
    thermistor_16 = unpack_right_shift_u16(src_p[3], 6u, 0xc0u);
    thermistor_16 |= unpack_left_shift_u16(src_p[4], 2u, 0xffu);

    if ((thermistor_16 & (1u << 9)) != 0u) {
        thermistor_16 |= 0xfc00u;
    }

    dst_p->thermistor_16 = (int16_t)thermistor_16;
    thermistor_17 = unpack_right_shift_u16(src_p[5], 0u, 0xffu);
    thermistor_17 |= unpack_left_shift_u16(src_p[6], 8u, 0x03u);

    if ((thermistor_17 & (1u << 9)) != 0u) {
        thermistor_17 |= 0xfc00u;
    }

    dst_p->thermistor_17 = (int16_t)thermistor_17;
    thermistor_18 = unpack_right_shift_u16(src_p[6], 2u, 0xfcu);
    thermistor_18 |= unpack_left_shift_u16(src_p[7], 6u, 0x0fu);

    if ((thermistor_18 & (1u << 9)) != 0u) {
        thermistor_18 |= 0xfc00u;
    }

    dst_p->thermistor_18 = (int16_t)thermistor_18;

    return (0);
}

int can_lib_thermistors_2_a_init(struct can_lib_thermistors_2_a_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct can_lib_thermistors_2_a_t));

    return 0;
}

int16_t can_lib_thermistors_2_a_thermistor_13_encode(double value)
{
    return (int16_t)(value);
}

double can_lib_thermistors_2_a_thermistor_13_decode(int16_t value)
{
    return ((double)value);
}

bool can_lib_thermistors_2_a_thermistor_13_is_in_range(int16_t value)
{
    return ((value >= -20) && (value <= 120));
}

bool can_lib_thermistors_2_a_thermistor_13_is_in_phys_range(double value)
{
    return ((value >= -20.0) && (value <= 120.0));
}

int16_t can_lib_thermistors_2_a_thermistor_14_encode(double value)
{
    return (int16_t)(value);
}

double can_lib_thermistors_2_a_thermistor_14_decode(int16_t value)
{
    return ((double)value);
}

bool can_lib_thermistors_2_a_thermistor_14_is_in_range(int16_t value)
{
    return ((value >= -20) && (value <= 120));
}

bool can_lib_thermistors_2_a_thermistor_14_is_in_phys_range(double value)
{
    return ((value >= -20.0) && (value <= 120.0));
}

int16_t can_lib_thermistors_2_a_thermistor_15_encode(double value)
{
    return (int16_t)(value);
}

double can_lib_thermistors_2_a_thermistor_15_decode(int16_t value)
{
    return ((double)value);
}

bool can_lib_thermistors_2_a_thermistor_15_is_in_range(int16_t value)
{
    return ((value >= -20) && (value <= 120));
}

bool can_lib_thermistors_2_a_thermistor_15_is_in_phys_range(double value)
{
    return ((value >= -20.0) && (value <= 120.0));
}

int16_t can_lib_thermistors_2_a_thermistor_16_encode(double value)
{
    return (int16_t)(value);
}

double can_lib_thermistors_2_a_thermistor_16_decode(int16_t value)
{
    return ((double)value);
}

bool can_lib_thermistors_2_a_thermistor_16_is_in_range(int16_t value)
{
    return ((value >= -20) && (value <= 120));
}

bool can_lib_thermistors_2_a_thermistor_16_is_in_phys_range(double value)
{
    return ((value >= -20.0) && (value <= 120.0));
}

int16_t can_lib_thermistors_2_a_thermistor_17_encode(double value)
{
    return (int16_t)(value);
}

double can_lib_thermistors_2_a_thermistor_17_decode(int16_t value)
{
    return ((double)value);
}

bool can_lib_thermistors_2_a_thermistor_17_is_in_range(int16_t value)
{
    return ((value >= -20) && (value <= 120));
}

bool can_lib_thermistors_2_a_thermistor_17_is_in_phys_range(double value)
{
    return ((value >= -20.0) && (value <= 120.0));
}

int16_t can_lib_thermistors_2_a_thermistor_18_encode(double value)
{
    return (int16_t)(value);
}

double can_lib_thermistors_2_a_thermistor_18_decode(int16_t value)
{
    return ((double)value);
}

bool can_lib_thermistors_2_a_thermistor_18_is_in_range(int16_t value)
{
    return ((value >= -20) && (value <= 120));
}

bool can_lib_thermistors_2_a_thermistor_18_is_in_phys_range(double value)
{
    return ((value >= -20.0) && (value <= 120.0));
}

int can_lib_thermistors_3_a_pack(
    uint8_t *dst_p,
    const struct can_lib_thermistors_3_a_t *src_p,
    size_t size)
{
    uint16_t thermistor_19;
    uint16_t thermistor_20;
    uint16_t thermistor_21;
    uint16_t thermistor_22;
    uint16_t thermistor_23;
    uint16_t thermistor_24;

    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    thermistor_19 = (uint16_t)src_p->thermistor_19;
    dst_p[0] |= pack_left_shift_u16(thermistor_19, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u16(thermistor_19, 8u, 0x03u);
    thermistor_20 = (uint16_t)src_p->thermistor_20;
    dst_p[1] |= pack_left_shift_u16(thermistor_20, 2u, 0xfcu);
    dst_p[2] |= pack_right_shift_u16(thermistor_20, 6u, 0x0fu);
    thermistor_21 = (uint16_t)src_p->thermistor_21;
    dst_p[2] |= pack_left_shift_u16(thermistor_21, 4u, 0xf0u);
    dst_p[3] |= pack_right_shift_u16(thermistor_21, 4u, 0x3fu);
    thermistor_22 = (uint16_t)src_p->thermistor_22;
    dst_p[3] |= pack_left_shift_u16(thermistor_22, 6u, 0xc0u);
    dst_p[4] |= pack_right_shift_u16(thermistor_22, 2u, 0xffu);
    thermistor_23 = (uint16_t)src_p->thermistor_23;
    dst_p[5] |= pack_left_shift_u16(thermistor_23, 0u, 0xffu);
    dst_p[6] |= pack_right_shift_u16(thermistor_23, 8u, 0x03u);
    thermistor_24 = (uint16_t)src_p->thermistor_24;
    dst_p[6] |= pack_left_shift_u16(thermistor_24, 2u, 0xfcu);
    dst_p[7] |= pack_right_shift_u16(thermistor_24, 6u, 0x0fu);

    return (8);
}

int can_lib_thermistors_3_a_unpack(
    struct can_lib_thermistors_3_a_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    uint16_t thermistor_19;
    uint16_t thermistor_20;
    uint16_t thermistor_21;
    uint16_t thermistor_22;
    uint16_t thermistor_23;
    uint16_t thermistor_24;

    if (size < 8u) {
        return (-EINVAL);
    }

    thermistor_19 = unpack_right_shift_u16(src_p[0], 0u, 0xffu);
    thermistor_19 |= unpack_left_shift_u16(src_p[1], 8u, 0x03u);

    if ((thermistor_19 & (1u << 9)) != 0u) {
        thermistor_19 |= 0xfc00u;
    }

    dst_p->thermistor_19 = (int16_t)thermistor_19;
    thermistor_20 = unpack_right_shift_u16(src_p[1], 2u, 0xfcu);
    thermistor_20 |= unpack_left_shift_u16(src_p[2], 6u, 0x0fu);

    if ((thermistor_20 & (1u << 9)) != 0u) {
        thermistor_20 |= 0xfc00u;
    }

    dst_p->thermistor_20 = (int16_t)thermistor_20;
    thermistor_21 = unpack_right_shift_u16(src_p[2], 4u, 0xf0u);
    thermistor_21 |= unpack_left_shift_u16(src_p[3], 4u, 0x3fu);

    if ((thermistor_21 & (1u << 9)) != 0u) {
        thermistor_21 |= 0xfc00u;
    }

    dst_p->thermistor_21 = (int16_t)thermistor_21;
    thermistor_22 = unpack_right_shift_u16(src_p[3], 6u, 0xc0u);
    thermistor_22 |= unpack_left_shift_u16(src_p[4], 2u, 0xffu);

    if ((thermistor_22 & (1u << 9)) != 0u) {
        thermistor_22 |= 0xfc00u;
    }

    dst_p->thermistor_22 = (int16_t)thermistor_22;
    thermistor_23 = unpack_right_shift_u16(src_p[5], 0u, 0xffu);
    thermistor_23 |= unpack_left_shift_u16(src_p[6], 8u, 0x03u);

    if ((thermistor_23 & (1u << 9)) != 0u) {
        thermistor_23 |= 0xfc00u;
    }

    dst_p->thermistor_23 = (int16_t)thermistor_23;
    thermistor_24 = unpack_right_shift_u16(src_p[6], 2u, 0xfcu);
    thermistor_24 |= unpack_left_shift_u16(src_p[7], 6u, 0x0fu);

    if ((thermistor_24 & (1u << 9)) != 0u) {
        thermistor_24 |= 0xfc00u;
    }

    dst_p->thermistor_24 = (int16_t)thermistor_24;

    return (0);
}

int can_lib_thermistors_3_a_init(struct can_lib_thermistors_3_a_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct can_lib_thermistors_3_a_t));

    return 0;
}

int16_t can_lib_thermistors_3_a_thermistor_19_encode(double value)
{
    return (int16_t)(value);
}

double can_lib_thermistors_3_a_thermistor_19_decode(int16_t value)
{
    return ((double)value);
}

bool can_lib_thermistors_3_a_thermistor_19_is_in_range(int16_t value)
{
    return ((value >= -20) && (value <= 120));
}

bool can_lib_thermistors_3_a_thermistor_19_is_in_phys_range(double value)
{
    return ((value >= -20.0) && (value <= 120.0));
}

int16_t can_lib_thermistors_3_a_thermistor_20_encode(double value)
{
    return (int16_t)(value);
}

double can_lib_thermistors_3_a_thermistor_20_decode(int16_t value)
{
    return ((double)value);
}

bool can_lib_thermistors_3_a_thermistor_20_is_in_range(int16_t value)
{
    return ((value >= -20) && (value <= 120));
}

bool can_lib_thermistors_3_a_thermistor_20_is_in_phys_range(double value)
{
    return ((value >= -20.0) && (value <= 120.0));
}

int16_t can_lib_thermistors_3_a_thermistor_21_encode(double value)
{
    return (int16_t)(value);
}

double can_lib_thermistors_3_a_thermistor_21_decode(int16_t value)
{
    return ((double)value);
}

bool can_lib_thermistors_3_a_thermistor_21_is_in_range(int16_t value)
{
    return ((value >= -20) && (value <= 120));
}

bool can_lib_thermistors_3_a_thermistor_21_is_in_phys_range(double value)
{
    return ((value >= -20.0) && (value <= 120.0));
}

int16_t can_lib_thermistors_3_a_thermistor_22_encode(double value)
{
    return (int16_t)(value);
}

double can_lib_thermistors_3_a_thermistor_22_decode(int16_t value)
{
    return ((double)value);
}

bool can_lib_thermistors_3_a_thermistor_22_is_in_range(int16_t value)
{
    return ((value >= -20) && (value <= 120));
}

bool can_lib_thermistors_3_a_thermistor_22_is_in_phys_range(double value)
{
    return ((value >= -20.0) && (value <= 120.0));
}

int16_t can_lib_thermistors_3_a_thermistor_23_encode(double value)
{
    return (int16_t)(value);
}

double can_lib_thermistors_3_a_thermistor_23_decode(int16_t value)
{
    return ((double)value);
}

bool can_lib_thermistors_3_a_thermistor_23_is_in_range(int16_t value)
{
    return ((value >= -20) && (value <= 120));
}

bool can_lib_thermistors_3_a_thermistor_23_is_in_phys_range(double value)
{
    return ((value >= -20.0) && (value <= 120.0));
}

int16_t can_lib_thermistors_3_a_thermistor_24_encode(double value)
{
    return (int16_t)(value);
}

double can_lib_thermistors_3_a_thermistor_24_decode(int16_t value)
{
    return ((double)value);
}

bool can_lib_thermistors_3_a_thermistor_24_is_in_range(int16_t value)
{
    return ((value >= -20) && (value <= 120));
}

bool can_lib_thermistors_3_a_thermistor_24_is_in_phys_range(double value)
{
    return ((value >= -20.0) && (value <= 120.0));
}

int can_lib_thermistors_4_a_pack(
    uint8_t *dst_p,
    const struct can_lib_thermistors_4_a_t *src_p,
    size_t size)
{
    uint16_t thermistor_25;
    uint16_t thermistor_26;
    uint16_t thermistor_27;
    uint16_t thermistor_28;
    uint16_t thermistor_29;
    uint16_t thermistor_30;

    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    thermistor_25 = (uint16_t)src_p->thermistor_25;
    dst_p[0] |= pack_left_shift_u16(thermistor_25, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u16(thermistor_25, 8u, 0x03u);
    thermistor_26 = (uint16_t)src_p->thermistor_26;
    dst_p[1] |= pack_left_shift_u16(thermistor_26, 2u, 0xfcu);
    dst_p[2] |= pack_right_shift_u16(thermistor_26, 6u, 0x0fu);
    thermistor_27 = (uint16_t)src_p->thermistor_27;
    dst_p[2] |= pack_left_shift_u16(thermistor_27, 4u, 0xf0u);
    dst_p[3] |= pack_right_shift_u16(thermistor_27, 4u, 0x3fu);
    thermistor_28 = (uint16_t)src_p->thermistor_28;
    dst_p[3] |= pack_left_shift_u16(thermistor_28, 6u, 0xc0u);
    dst_p[4] |= pack_right_shift_u16(thermistor_28, 2u, 0xffu);
    thermistor_29 = (uint16_t)src_p->thermistor_29;
    dst_p[5] |= pack_left_shift_u16(thermistor_29, 0u, 0xffu);
    dst_p[6] |= pack_right_shift_u16(thermistor_29, 8u, 0x03u);
    thermistor_30 = (uint16_t)src_p->thermistor_30;
    dst_p[6] |= pack_left_shift_u16(thermistor_30, 2u, 0xfcu);
    dst_p[7] |= pack_right_shift_u16(thermistor_30, 6u, 0x0fu);

    return (8);
}

int can_lib_thermistors_4_a_unpack(
    struct can_lib_thermistors_4_a_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    uint16_t thermistor_25;
    uint16_t thermistor_26;
    uint16_t thermistor_27;
    uint16_t thermistor_28;
    uint16_t thermistor_29;
    uint16_t thermistor_30;

    if (size < 8u) {
        return (-EINVAL);
    }

    thermistor_25 = unpack_right_shift_u16(src_p[0], 0u, 0xffu);
    thermistor_25 |= unpack_left_shift_u16(src_p[1], 8u, 0x03u);

    if ((thermistor_25 & (1u << 9)) != 0u) {
        thermistor_25 |= 0xfc00u;
    }

    dst_p->thermistor_25 = (int16_t)thermistor_25;
    thermistor_26 = unpack_right_shift_u16(src_p[1], 2u, 0xfcu);
    thermistor_26 |= unpack_left_shift_u16(src_p[2], 6u, 0x0fu);

    if ((thermistor_26 & (1u << 9)) != 0u) {
        thermistor_26 |= 0xfc00u;
    }

    dst_p->thermistor_26 = (int16_t)thermistor_26;
    thermistor_27 = unpack_right_shift_u16(src_p[2], 4u, 0xf0u);
    thermistor_27 |= unpack_left_shift_u16(src_p[3], 4u, 0x3fu);

    if ((thermistor_27 & (1u << 9)) != 0u) {
        thermistor_27 |= 0xfc00u;
    }

    dst_p->thermistor_27 = (int16_t)thermistor_27;
    thermistor_28 = unpack_right_shift_u16(src_p[3], 6u, 0xc0u);
    thermistor_28 |= unpack_left_shift_u16(src_p[4], 2u, 0xffu);

    if ((thermistor_28 & (1u << 9)) != 0u) {
        thermistor_28 |= 0xfc00u;
    }

    dst_p->thermistor_28 = (int16_t)thermistor_28;
    thermistor_29 = unpack_right_shift_u16(src_p[5], 0u, 0xffu);
    thermistor_29 |= unpack_left_shift_u16(src_p[6], 8u, 0x03u);

    if ((thermistor_29 & (1u << 9)) != 0u) {
        thermistor_29 |= 0xfc00u;
    }

    dst_p->thermistor_29 = (int16_t)thermistor_29;
    thermistor_30 = unpack_right_shift_u16(src_p[6], 2u, 0xfcu);
    thermistor_30 |= unpack_left_shift_u16(src_p[7], 6u, 0x0fu);

    if ((thermistor_30 & (1u << 9)) != 0u) {
        thermistor_30 |= 0xfc00u;
    }

    dst_p->thermistor_30 = (int16_t)thermistor_30;

    return (0);
}

int can_lib_thermistors_4_a_init(struct can_lib_thermistors_4_a_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct can_lib_thermistors_4_a_t));

    return 0;
}

int16_t can_lib_thermistors_4_a_thermistor_25_encode(double value)
{
    return (int16_t)(value);
}

double can_lib_thermistors_4_a_thermistor_25_decode(int16_t value)
{
    return ((double)value);
}

bool can_lib_thermistors_4_a_thermistor_25_is_in_range(int16_t value)
{
    return ((value >= -20) && (value <= 120));
}

bool can_lib_thermistors_4_a_thermistor_25_is_in_phys_range(double value)
{
    return ((value >= -20.0) && (value <= 120.0));
}

int16_t can_lib_thermistors_4_a_thermistor_26_encode(double value)
{
    return (int16_t)(value);
}

double can_lib_thermistors_4_a_thermistor_26_decode(int16_t value)
{
    return ((double)value);
}

bool can_lib_thermistors_4_a_thermistor_26_is_in_range(int16_t value)
{
    return ((value >= -20) && (value <= 120));
}

bool can_lib_thermistors_4_a_thermistor_26_is_in_phys_range(double value)
{
    return ((value >= -20.0) && (value <= 120.0));
}

int16_t can_lib_thermistors_4_a_thermistor_27_encode(double value)
{
    return (int16_t)(value);
}

double can_lib_thermistors_4_a_thermistor_27_decode(int16_t value)
{
    return ((double)value);
}

bool can_lib_thermistors_4_a_thermistor_27_is_in_range(int16_t value)
{
    return ((value >= -20) && (value <= 120));
}

bool can_lib_thermistors_4_a_thermistor_27_is_in_phys_range(double value)
{
    return ((value >= -20.0) && (value <= 120.0));
}

int16_t can_lib_thermistors_4_a_thermistor_28_encode(double value)
{
    return (int16_t)(value);
}

double can_lib_thermistors_4_a_thermistor_28_decode(int16_t value)
{
    return ((double)value);
}

bool can_lib_thermistors_4_a_thermistor_28_is_in_range(int16_t value)
{
    return ((value >= -20) && (value <= 120));
}

bool can_lib_thermistors_4_a_thermistor_28_is_in_phys_range(double value)
{
    return ((value >= -20.0) && (value <= 120.0));
}

int16_t can_lib_thermistors_4_a_thermistor_29_encode(double value)
{
    return (int16_t)(value);
}

double can_lib_thermistors_4_a_thermistor_29_decode(int16_t value)
{
    return ((double)value);
}

bool can_lib_thermistors_4_a_thermistor_29_is_in_range(int16_t value)
{
    return ((value >= -20) && (value <= 120));
}

bool can_lib_thermistors_4_a_thermistor_29_is_in_phys_range(double value)
{
    return ((value >= -20.0) && (value <= 120.0));
}

int16_t can_lib_thermistors_4_a_thermistor_30_encode(double value)
{
    return (int16_t)(value);
}

double can_lib_thermistors_4_a_thermistor_30_decode(int16_t value)
{
    return ((double)value);
}

bool can_lib_thermistors_4_a_thermistor_30_is_in_range(int16_t value)
{
    return ((value >= -20) && (value <= 120));
}

bool can_lib_thermistors_4_a_thermistor_30_is_in_phys_range(double value)
{
    return ((value >= -20.0) && (value <= 120.0));
}

int can_lib_core_status_pack(
    uint8_t *dst_p,
    const struct can_lib_core_status_t *src_p,
    size_t size)
{
    if (size < 1u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 1);

    dst_p[0] |= pack_left_shift_u8(src_p->core_state, 0u, 0x07u);

    return (1);
}

int can_lib_core_status_unpack(
    struct can_lib_core_status_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 1u) {
        return (-EINVAL);
    }

    dst_p->core_state = unpack_right_shift_u8(src_p[0], 0u, 0x07u);

    return (0);
}

int can_lib_core_status_init(struct can_lib_core_status_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct can_lib_core_status_t));

    return 0;
}

uint8_t can_lib_core_status_core_state_encode(double value)
{
    return (uint8_t)(value);
}

double can_lib_core_status_core_state_decode(uint8_t value)
{
    return ((double)value);
}

bool can_lib_core_status_core_state_is_in_range(uint8_t value)
{
    return (value <= 7u);
}

bool can_lib_core_status_core_state_is_in_phys_range(double value)
{
    (void)value;

    return (true);
}

int can_lib_core_batt_ctrl_pack(
    uint8_t *dst_p,
    const struct can_lib_core_batt_ctrl_t *src_p,
    size_t size)
{
    if (size < 1u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 1);

    dst_p[0] |= pack_left_shift_u8(src_p->north, 3u, 0x08u);
    dst_p[0] |= pack_left_shift_u8(src_p->east, 4u, 0x10u);
    dst_p[0] |= pack_left_shift_u8(src_p->west, 5u, 0x20u);
    dst_p[0] |= pack_left_shift_u8(src_p->south, 6u, 0x40u);

    return (1);
}

int can_lib_core_batt_ctrl_unpack(
    struct can_lib_core_batt_ctrl_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 1u) {
        return (-EINVAL);
    }

    dst_p->north = unpack_right_shift_u8(src_p[0], 3u, 0x08u);
    dst_p->east = unpack_right_shift_u8(src_p[0], 4u, 0x10u);
    dst_p->west = unpack_right_shift_u8(src_p[0], 5u, 0x20u);
    dst_p->south = unpack_right_shift_u8(src_p[0], 6u, 0x40u);

    return (0);
}

int can_lib_core_batt_ctrl_init(struct can_lib_core_batt_ctrl_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct can_lib_core_batt_ctrl_t));

    return 0;
}

uint8_t can_lib_core_batt_ctrl_north_encode(double value)
{
    return (uint8_t)(value);
}

double can_lib_core_batt_ctrl_north_decode(uint8_t value)
{
    return ((double)value);
}

bool can_lib_core_batt_ctrl_north_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

bool can_lib_core_batt_ctrl_north_is_in_phys_range(double value)
{
    (void)value;

    return (true);
}

uint8_t can_lib_core_batt_ctrl_east_encode(double value)
{
    return (uint8_t)(value);
}

double can_lib_core_batt_ctrl_east_decode(uint8_t value)
{
    return ((double)value);
}

bool can_lib_core_batt_ctrl_east_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

bool can_lib_core_batt_ctrl_east_is_in_phys_range(double value)
{
    (void)value;

    return (true);
}

uint8_t can_lib_core_batt_ctrl_west_encode(double value)
{
    return (uint8_t)(value);
}

double can_lib_core_batt_ctrl_west_decode(uint8_t value)
{
    return ((double)value);
}

bool can_lib_core_batt_ctrl_west_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

bool can_lib_core_batt_ctrl_west_is_in_phys_range(double value)
{
    (void)value;

    return (true);
}

uint8_t can_lib_core_batt_ctrl_south_encode(double value)
{
    return (uint8_t)(value);
}

double can_lib_core_batt_ctrl_south_decode(uint8_t value)
{
    return ((double)value);
}

bool can_lib_core_batt_ctrl_south_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

bool can_lib_core_batt_ctrl_south_is_in_phys_range(double value)
{
    (void)value;

    return (true);
}

int can_lib_charger_status_pack(
    uint8_t *dst_p,
    const struct can_lib_charger_status_t *src_p,
    size_t size)
{
    if (size < 6u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 6);

    dst_p[0] |= pack_left_shift_u8(src_p->charger_state, 0u, 0x07u);
    dst_p[0] |= pack_left_shift_u16(src_p->voltage_target, 3u, 0xf8u);
    dst_p[1] |= pack_right_shift_u16(src_p->voltage_target, 5u, 0xffu);
    dst_p[2] |= pack_right_shift_u16(src_p->voltage_target, 13u, 0x07u);
    dst_p[2] |= pack_left_shift_u16(src_p->output_voltage, 3u, 0xf8u);
    dst_p[3] |= pack_right_shift_u16(src_p->output_voltage, 5u, 0xffu);
    dst_p[4] |= pack_right_shift_u16(src_p->output_voltage, 13u, 0x07u);
    dst_p[4] |= pack_left_shift_u16(src_p->output_current, 3u, 0xf8u);
    dst_p[5] |= pack_right_shift_u16(src_p->output_current, 5u, 0x1fu);

    return (6);
}

int can_lib_charger_status_unpack(
    struct can_lib_charger_status_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 6u) {
        return (-EINVAL);
    }

    dst_p->charger_state = unpack_right_shift_u8(src_p[0], 0u, 0x07u);
    dst_p->voltage_target = unpack_right_shift_u16(src_p[0], 3u, 0xf8u);
    dst_p->voltage_target |= unpack_left_shift_u16(src_p[1], 5u, 0xffu);
    dst_p->voltage_target |= unpack_left_shift_u16(src_p[2], 13u, 0x07u);
    dst_p->output_voltage = unpack_right_shift_u16(src_p[2], 3u, 0xf8u);
    dst_p->output_voltage |= unpack_left_shift_u16(src_p[3], 5u, 0xffu);
    dst_p->output_voltage |= unpack_left_shift_u16(src_p[4], 13u, 0x07u);
    dst_p->output_current = unpack_right_shift_u16(src_p[4], 3u, 0xf8u);
    dst_p->output_current |= unpack_left_shift_u16(src_p[5], 5u, 0x1fu);

    return (0);
}

int can_lib_charger_status_init(struct can_lib_charger_status_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct can_lib_charger_status_t));

    return 0;
}

uint8_t can_lib_charger_status_charger_state_encode(double value)
{
    return (uint8_t)(value);
}

double can_lib_charger_status_charger_state_decode(uint8_t value)
{
    return ((double)value);
}

bool can_lib_charger_status_charger_state_is_in_range(uint8_t value)
{
    return (value <= 7u);
}

bool can_lib_charger_status_charger_state_is_in_phys_range(double value)
{
    (void)value;

    return (true);
}

uint16_t can_lib_charger_status_voltage_target_encode(double value)
{
    return (uint16_t)(value);
}

double can_lib_charger_status_voltage_target_decode(uint16_t value)
{
    return ((double)value);
}

bool can_lib_charger_status_voltage_target_is_in_range(uint16_t value)
{
    return (value <= 70u);
}

bool can_lib_charger_status_voltage_target_is_in_phys_range(double value)
{
    return ((value >= 0.0) && (value <= 70.0));
}

uint16_t can_lib_charger_status_output_voltage_encode(double value)
{
    return (uint16_t)(value);
}

double can_lib_charger_status_output_voltage_decode(uint16_t value)
{
    return ((double)value);
}

bool can_lib_charger_status_output_voltage_is_in_range(uint16_t value)
{
    return (value <= 70u);
}

bool can_lib_charger_status_output_voltage_is_in_phys_range(double value)
{
    return ((value >= 0.0) && (value <= 70.0));
}

uint16_t can_lib_charger_status_output_current_encode(double value)
{
    return (uint16_t)(value);
}

double can_lib_charger_status_output_current_decode(uint16_t value)
{
    return ((double)value);
}

bool can_lib_charger_status_output_current_is_in_range(uint16_t value)
{
    return (value <= 100u);
}

bool can_lib_charger_status_output_current_is_in_phys_range(double value)
{
    return ((value >= 0.0) && (value <= 100.0));
}
