/**
 * @file can_lib.c
 *
 * @brief This source file was generated by cantools version 41.0.2 Thu Apr  9 00:02:00 2026.
 *
 * @copyright Copyright (c) 2018-2019 Erik Moqvist
 *
 * @par License
 * The MIT License (MIT)
 *
 * Permission is hereby granted, free of charge, to any person
 * obtaining a copy of this software and associated documentation
 * files (the "Software"), to deal in the Software without
 * restriction, including without limitation the rights to use, copy,
 * modify, merge, publish, distribute, sublicense, and/or sell copies
 * of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be
 * included in all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 * NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS
 * BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN
 * ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
 * CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

#include <string.h>

#include "can_lib.h"

static inline uint8_t pack_left_shift_u8(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value << shift) & mask);
}

static inline uint8_t pack_left_shift_u16(
    uint16_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value << shift) & mask);
}

static inline uint8_t pack_right_shift_u16(
    uint16_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value >> shift) & mask);
}

static inline uint16_t unpack_left_shift_u16(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint16_t)((uint16_t)(value & mask) << shift);
}

static inline uint8_t unpack_right_shift_u8(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value & mask) >> shift);
}

static inline uint16_t unpack_right_shift_u16(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint16_t)((uint16_t)(value & mask) >> shift);
}

int can_lib_msg1_pack(
    uint8_t *dst_p,
    const struct can_lib_msg1_t *src_p,
    size_t size)
{
    if (size < 7u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 7);

    dst_p[0] |= pack_left_shift_u16(src_p->rpm, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u16(src_p->rpm, 8u, 0xffu);
    dst_p[2] |= pack_left_shift_u16(src_p->pwm, 0u, 0xffu);
    dst_p[3] |= pack_right_shift_u16(src_p->pwm, 8u, 0xffu);
    dst_p[4] |= pack_left_shift_u8(src_p->overvoltage, 0u, 0x01u);
    dst_p[4] |= pack_left_shift_u8(src_p->undervoltage, 1u, 0x02u);
    dst_p[4] |= pack_left_shift_u8(src_p->overcurrent, 2u, 0x04u);
    dst_p[4] |= pack_left_shift_u8(src_p->positioning_complete, 3u, 0x08u);
    dst_p[4] |= pack_left_shift_u8(src_p->throttle_lost, 4u, 0x10u);
    dst_p[4] |= pack_left_shift_u8(src_p->throttle_not_zero, 5u, 0x20u);
    dst_p[4] |= pack_left_shift_u8(src_p->mos_overheat, 6u, 0x40u);
    dst_p[4] |= pack_left_shift_u8(src_p->capacitor_overheat, 7u, 0x80u);
    dst_p[5] |= pack_left_shift_u8(src_p->stall, 0u, 0x01u);
    dst_p[5] |= pack_left_shift_u8(src_p->mos_open, 1u, 0x02u);
    dst_p[5] |= pack_left_shift_u8(src_p->mos_short_circuit, 2u, 0x04u);
    dst_p[5] |= pack_left_shift_u8(src_p->motor_disconnection, 3u, 0x08u);
    dst_p[5] |= pack_left_shift_u8(src_p->op_amp_exception, 4u, 0x10u);
    dst_p[5] |= pack_left_shift_u8(src_p->comm_status, 5u, 0x20u);
    dst_p[5] |= pack_left_shift_u8(src_p->direction_flag, 6u, 0x40u);
    dst_p[5] |= pack_left_shift_u8(src_p->throttle_source, 7u, 0x80u);
    dst_p[6] |= pack_left_shift_u8(src_p->tail_byte, 0u, 0xffu);

    return (7);
}

int can_lib_msg1_unpack(
    struct can_lib_msg1_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 7u) {
        return (-EINVAL);
    }

    dst_p->rpm = unpack_right_shift_u16(src_p[0], 0u, 0xffu);
    dst_p->rpm |= unpack_left_shift_u16(src_p[1], 8u, 0xffu);
    dst_p->pwm = unpack_right_shift_u16(src_p[2], 0u, 0xffu);
    dst_p->pwm |= unpack_left_shift_u16(src_p[3], 8u, 0xffu);
    dst_p->overvoltage = unpack_right_shift_u8(src_p[4], 0u, 0x01u);
    dst_p->undervoltage = unpack_right_shift_u8(src_p[4], 1u, 0x02u);
    dst_p->overcurrent = unpack_right_shift_u8(src_p[4], 2u, 0x04u);
    dst_p->positioning_complete = unpack_right_shift_u8(src_p[4], 3u, 0x08u);
    dst_p->throttle_lost = unpack_right_shift_u8(src_p[4], 4u, 0x10u);
    dst_p->throttle_not_zero = unpack_right_shift_u8(src_p[4], 5u, 0x20u);
    dst_p->mos_overheat = unpack_right_shift_u8(src_p[4], 6u, 0x40u);
    dst_p->capacitor_overheat = unpack_right_shift_u8(src_p[4], 7u, 0x80u);
    dst_p->stall = unpack_right_shift_u8(src_p[5], 0u, 0x01u);
    dst_p->mos_open = unpack_right_shift_u8(src_p[5], 1u, 0x02u);
    dst_p->mos_short_circuit = unpack_right_shift_u8(src_p[5], 2u, 0x04u);
    dst_p->motor_disconnection = unpack_right_shift_u8(src_p[5], 3u, 0x08u);
    dst_p->op_amp_exception = unpack_right_shift_u8(src_p[5], 4u, 0x10u);
    dst_p->comm_status = unpack_right_shift_u8(src_p[5], 5u, 0x20u);
    dst_p->direction_flag = unpack_right_shift_u8(src_p[5], 6u, 0x40u);
    dst_p->throttle_source = unpack_right_shift_u8(src_p[5], 7u, 0x80u);
    dst_p->tail_byte = unpack_right_shift_u8(src_p[6], 0u, 0xffu);

    return (0);
}

int can_lib_msg1_init(struct can_lib_msg1_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct can_lib_msg1_t));

    return 0;
}

uint16_t can_lib_msg1_rpm_encode(double value)
{
    return (uint16_t)(value);
}

double can_lib_msg1_rpm_decode(uint16_t value)
{
    return ((double)value);
}

bool can_lib_msg1_rpm_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

uint16_t can_lib_msg1_pwm_encode(double value)
{
    return (uint16_t)(value);
}

double can_lib_msg1_pwm_decode(uint16_t value)
{
    return ((double)value);
}

bool can_lib_msg1_pwm_is_in_range(uint16_t value)
{
    return (value <= 8191u);
}

uint8_t can_lib_msg1_overvoltage_encode(double value)
{
    return (uint8_t)(value);
}

double can_lib_msg1_overvoltage_decode(uint8_t value)
{
    return ((double)value);
}

bool can_lib_msg1_overvoltage_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t can_lib_msg1_undervoltage_encode(double value)
{
    return (uint8_t)(value);
}

double can_lib_msg1_undervoltage_decode(uint8_t value)
{
    return ((double)value);
}

bool can_lib_msg1_undervoltage_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t can_lib_msg1_overcurrent_encode(double value)
{
    return (uint8_t)(value);
}

double can_lib_msg1_overcurrent_decode(uint8_t value)
{
    return ((double)value);
}

bool can_lib_msg1_overcurrent_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t can_lib_msg1_positioning_complete_encode(double value)
{
    return (uint8_t)(value);
}

double can_lib_msg1_positioning_complete_decode(uint8_t value)
{
    return ((double)value);
}

bool can_lib_msg1_positioning_complete_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t can_lib_msg1_throttle_lost_encode(double value)
{
    return (uint8_t)(value);
}

double can_lib_msg1_throttle_lost_decode(uint8_t value)
{
    return ((double)value);
}

bool can_lib_msg1_throttle_lost_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t can_lib_msg1_throttle_not_zero_encode(double value)
{
    return (uint8_t)(value);
}

double can_lib_msg1_throttle_not_zero_decode(uint8_t value)
{
    return ((double)value);
}

bool can_lib_msg1_throttle_not_zero_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t can_lib_msg1_mos_overheat_encode(double value)
{
    return (uint8_t)(value);
}

double can_lib_msg1_mos_overheat_decode(uint8_t value)
{
    return ((double)value);
}

bool can_lib_msg1_mos_overheat_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t can_lib_msg1_capacitor_overheat_encode(double value)
{
    return (uint8_t)(value);
}

double can_lib_msg1_capacitor_overheat_decode(uint8_t value)
{
    return ((double)value);
}

bool can_lib_msg1_capacitor_overheat_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t can_lib_msg1_stall_encode(double value)
{
    return (uint8_t)(value);
}

double can_lib_msg1_stall_decode(uint8_t value)
{
    return ((double)value);
}

bool can_lib_msg1_stall_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t can_lib_msg1_mos_open_encode(double value)
{
    return (uint8_t)(value);
}

double can_lib_msg1_mos_open_decode(uint8_t value)
{
    return ((double)value);
}

bool can_lib_msg1_mos_open_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t can_lib_msg1_mos_short_circuit_encode(double value)
{
    return (uint8_t)(value);
}

double can_lib_msg1_mos_short_circuit_decode(uint8_t value)
{
    return ((double)value);
}

bool can_lib_msg1_mos_short_circuit_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t can_lib_msg1_motor_disconnection_encode(double value)
{
    return (uint8_t)(value);
}

double can_lib_msg1_motor_disconnection_decode(uint8_t value)
{
    return ((double)value);
}

bool can_lib_msg1_motor_disconnection_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t can_lib_msg1_op_amp_exception_encode(double value)
{
    return (uint8_t)(value);
}

double can_lib_msg1_op_amp_exception_decode(uint8_t value)
{
    return ((double)value);
}

bool can_lib_msg1_op_amp_exception_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t can_lib_msg1_comm_status_encode(double value)
{
    return (uint8_t)(value);
}

double can_lib_msg1_comm_status_decode(uint8_t value)
{
    return ((double)value);
}

bool can_lib_msg1_comm_status_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t can_lib_msg1_direction_flag_encode(double value)
{
    return (uint8_t)(value);
}

double can_lib_msg1_direction_flag_decode(uint8_t value)
{
    return ((double)value);
}

bool can_lib_msg1_direction_flag_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t can_lib_msg1_throttle_source_encode(double value)
{
    return (uint8_t)(value);
}

double can_lib_msg1_throttle_source_decode(uint8_t value)
{
    return ((double)value);
}

bool can_lib_msg1_throttle_source_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t can_lib_msg1_tail_byte_encode(double value)
{
    return (uint8_t)(value);
}

double can_lib_msg1_tail_byte_decode(uint8_t value)
{
    return ((double)value);
}

bool can_lib_msg1_tail_byte_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

int can_lib_msg2_pack(
    uint8_t *dst_p,
    const struct can_lib_msg2_t *src_p,
    size_t size)
{
    if (size < 6u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 6);

    dst_p[0] |= pack_left_shift_u16(src_p->voltage, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u16(src_p->voltage, 8u, 0xffu);
    dst_p[2] |= pack_left_shift_u16(src_p->current, 0u, 0xffu);
    dst_p[3] |= pack_right_shift_u16(src_p->current, 8u, 0xffu);
    dst_p[4] |= pack_left_shift_u8(src_p->temperature, 0u, 0xffu);
    dst_p[5] |= pack_left_shift_u8(src_p->tail_byte, 0u, 0xffu);

    return (6);
}

int can_lib_msg2_unpack(
    struct can_lib_msg2_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 6u) {
        return (-EINVAL);
    }

    dst_p->voltage = unpack_right_shift_u16(src_p[0], 0u, 0xffu);
    dst_p->voltage |= unpack_left_shift_u16(src_p[1], 8u, 0xffu);
    dst_p->current = unpack_right_shift_u16(src_p[2], 0u, 0xffu);
    dst_p->current |= unpack_left_shift_u16(src_p[3], 8u, 0xffu);
    dst_p->temperature = unpack_right_shift_u8(src_p[4], 0u, 0xffu);
    dst_p->tail_byte = unpack_right_shift_u8(src_p[5], 0u, 0xffu);

    return (0);
}

int can_lib_msg2_init(struct can_lib_msg2_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct can_lib_msg2_t));

    return 0;
}

uint16_t can_lib_msg2_voltage_encode(double value)
{
    return (uint16_t)(value / 0.1);
}

double can_lib_msg2_voltage_decode(uint16_t value)
{
    return ((double)value * 0.1);
}

bool can_lib_msg2_voltage_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

uint16_t can_lib_msg2_current_encode(double value)
{
    return (uint16_t)(value / 0.1);
}

double can_lib_msg2_current_decode(uint16_t value)
{
    return ((double)value * 0.1);
}

bool can_lib_msg2_current_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

uint8_t can_lib_msg2_temperature_encode(double value)
{
    return (uint8_t)(value);
}

double can_lib_msg2_temperature_decode(uint8_t value)
{
    return ((double)value);
}

bool can_lib_msg2_temperature_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t can_lib_msg2_tail_byte_encode(double value)
{
    return (uint8_t)(value);
}

double can_lib_msg2_tail_byte_decode(uint8_t value)
{
    return ((double)value);
}

bool can_lib_msg2_tail_byte_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

int can_lib_msg3_pack(
    uint8_t *dst_p,
    const struct can_lib_msg3_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_left_shift_u8(src_p->mos_t, 0u, 0xffu);
    dst_p[1] |= pack_left_shift_u8(src_p->cap_t, 0u, 0xffu);
    dst_p[2] |= pack_left_shift_u8(src_p->motor_t, 0u, 0xffu);
    dst_p[3] |= pack_left_shift_u8(src_p->reserved1, 0u, 0xffu);
    dst_p[4] |= pack_left_shift_u8(src_p->reserved2, 0u, 0xffu);
    dst_p[5] |= pack_left_shift_u8(src_p->reserved3, 0u, 0xffu);
    dst_p[6] |= pack_left_shift_u8(src_p->reserved4, 0u, 0xffu);
    dst_p[7] |= pack_left_shift_u8(src_p->tail_byte, 0u, 0xffu);

    return (8);
}

int can_lib_msg3_unpack(
    struct can_lib_msg3_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->mos_t = unpack_right_shift_u8(src_p[0], 0u, 0xffu);
    dst_p->cap_t = unpack_right_shift_u8(src_p[1], 0u, 0xffu);
    dst_p->motor_t = unpack_right_shift_u8(src_p[2], 0u, 0xffu);
    dst_p->reserved1 = unpack_right_shift_u8(src_p[3], 0u, 0xffu);
    dst_p->reserved2 = unpack_right_shift_u8(src_p[4], 0u, 0xffu);
    dst_p->reserved3 = unpack_right_shift_u8(src_p[5], 0u, 0xffu);
    dst_p->reserved4 = unpack_right_shift_u8(src_p[6], 0u, 0xffu);
    dst_p->tail_byte = unpack_right_shift_u8(src_p[7], 0u, 0xffu);

    return (0);
}

int can_lib_msg3_init(struct can_lib_msg3_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct can_lib_msg3_t));

    return 0;
}

uint8_t can_lib_msg3_mos_t_encode(double value)
{
    return (uint8_t)(value);
}

double can_lib_msg3_mos_t_decode(uint8_t value)
{
    return ((double)value);
}

bool can_lib_msg3_mos_t_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t can_lib_msg3_cap_t_encode(double value)
{
    return (uint8_t)(value);
}

double can_lib_msg3_cap_t_decode(uint8_t value)
{
    return ((double)value);
}

bool can_lib_msg3_cap_t_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t can_lib_msg3_motor_t_encode(double value)
{
    return (uint8_t)(value);
}

double can_lib_msg3_motor_t_decode(uint8_t value)
{
    return ((double)value);
}

bool can_lib_msg3_motor_t_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t can_lib_msg3_reserved1_encode(double value)
{
    return (uint8_t)(value);
}

double can_lib_msg3_reserved1_decode(uint8_t value)
{
    return ((double)value);
}

bool can_lib_msg3_reserved1_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t can_lib_msg3_reserved2_encode(double value)
{
    return (uint8_t)(value);
}

double can_lib_msg3_reserved2_decode(uint8_t value)
{
    return ((double)value);
}

bool can_lib_msg3_reserved2_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t can_lib_msg3_reserved3_encode(double value)
{
    return (uint8_t)(value);
}

double can_lib_msg3_reserved3_decode(uint8_t value)
{
    return ((double)value);
}

bool can_lib_msg3_reserved3_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t can_lib_msg3_reserved4_encode(double value)
{
    return (uint8_t)(value);
}

double can_lib_msg3_reserved4_decode(uint8_t value)
{
    return ((double)value);
}

bool can_lib_msg3_reserved4_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t can_lib_msg3_tail_byte_encode(double value)
{
    return (uint8_t)(value);
}

double can_lib_msg3_tail_byte_decode(uint8_t value)
{
    return ((double)value);
}

bool can_lib_msg3_tail_byte_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

int can_lib_thrust_pack(
    uint8_t *dst_p,
    const struct can_lib_thrust_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_left_shift_u8(src_p->b1, 0u, 0xffu);
    dst_p[1] |= pack_left_shift_u8(src_p->b2, 0u, 0xffu);
    dst_p[2] |= pack_left_shift_u8(src_p->b3, 0u, 0xffu);
    dst_p[3] |= pack_left_shift_u8(src_p->b4, 0u, 0xffu);
    dst_p[4] |= pack_left_shift_u8(src_p->b5, 0u, 0xffu);
    dst_p[5] |= pack_left_shift_u8(src_p->b6, 0u, 0xffu);
    dst_p[6] |= pack_left_shift_u8(src_p->b7, 0u, 0xffu);
    dst_p[7] |= pack_left_shift_u8(src_p->tail_byte, 0u, 0xffu);

    return (8);
}

int can_lib_thrust_unpack(
    struct can_lib_thrust_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->b1 = unpack_right_shift_u8(src_p[0], 0u, 0xffu);
    dst_p->b2 = unpack_right_shift_u8(src_p[1], 0u, 0xffu);
    dst_p->b3 = unpack_right_shift_u8(src_p[2], 0u, 0xffu);
    dst_p->b4 = unpack_right_shift_u8(src_p[3], 0u, 0xffu);
    dst_p->b5 = unpack_right_shift_u8(src_p[4], 0u, 0xffu);
    dst_p->b6 = unpack_right_shift_u8(src_p[5], 0u, 0xffu);
    dst_p->b7 = unpack_right_shift_u8(src_p[6], 0u, 0xffu);
    dst_p->tail_byte = unpack_right_shift_u8(src_p[7], 0u, 0xffu);

    return (0);
}

int can_lib_thrust_init(struct can_lib_thrust_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct can_lib_thrust_t));

    return 0;
}

uint8_t can_lib_thrust_b1_encode(double value)
{
    return (uint8_t)(value);
}

double can_lib_thrust_b1_decode(uint8_t value)
{
    return ((double)value);
}

bool can_lib_thrust_b1_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t can_lib_thrust_b2_encode(double value)
{
    return (uint8_t)(value);
}

double can_lib_thrust_b2_decode(uint8_t value)
{
    return ((double)value);
}

bool can_lib_thrust_b2_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t can_lib_thrust_b3_encode(double value)
{
    return (uint8_t)(value);
}

double can_lib_thrust_b3_decode(uint8_t value)
{
    return ((double)value);
}

bool can_lib_thrust_b3_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t can_lib_thrust_b4_encode(double value)
{
    return (uint8_t)(value);
}

double can_lib_thrust_b4_decode(uint8_t value)
{
    return ((double)value);
}

bool can_lib_thrust_b4_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t can_lib_thrust_b5_encode(double value)
{
    return (uint8_t)(value);
}

double can_lib_thrust_b5_decode(uint8_t value)
{
    return ((double)value);
}

bool can_lib_thrust_b5_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t can_lib_thrust_b6_encode(double value)
{
    return (uint8_t)(value);
}

double can_lib_thrust_b6_decode(uint8_t value)
{
    return ((double)value);
}

bool can_lib_thrust_b6_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t can_lib_thrust_b7_encode(double value)
{
    return (uint8_t)(value);
}

double can_lib_thrust_b7_decode(uint8_t value)
{
    return ((double)value);
}

bool can_lib_thrust_b7_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t can_lib_thrust_tail_byte_encode(double value)
{
    return (uint8_t)(value);
}

double can_lib_thrust_tail_byte_decode(uint8_t value)
{
    return ((double)value);
}

bool can_lib_thrust_tail_byte_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

int can_lib_thrust_short_pack(
    uint8_t *dst_p,
    const struct can_lib_thrust_short_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_left_shift_u8(src_p->b1, 0u, 0xffu);
    dst_p[1] |= pack_left_shift_u8(src_p->b2, 0u, 0xffu);
    dst_p[2] |= pack_left_shift_u8(src_p->tail_byte, 0u, 0xffu);

    return (8);
}

int can_lib_thrust_short_unpack(
    struct can_lib_thrust_short_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->b1 = unpack_right_shift_u8(src_p[0], 0u, 0xffu);
    dst_p->b2 = unpack_right_shift_u8(src_p[1], 0u, 0xffu);
    dst_p->tail_byte = unpack_right_shift_u8(src_p[2], 0u, 0xffu);

    return (0);
}

int can_lib_thrust_short_init(struct can_lib_thrust_short_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct can_lib_thrust_short_t));

    return 0;
}

uint8_t can_lib_thrust_short_b1_encode(double value)
{
    return (uint8_t)(value);
}

double can_lib_thrust_short_b1_decode(uint8_t value)
{
    return ((double)value);
}

bool can_lib_thrust_short_b1_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t can_lib_thrust_short_b2_encode(double value)
{
    return (uint8_t)(value);
}

double can_lib_thrust_short_b2_decode(uint8_t value)
{
    return ((double)value);
}

bool can_lib_thrust_short_b2_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t can_lib_thrust_short_tail_byte_encode(double value)
{
    return (uint8_t)(value);
}

double can_lib_thrust_short_tail_byte_decode(uint8_t value)
{
    return ((double)value);
}

bool can_lib_thrust_short_tail_byte_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

int can_lib_bms_status_pack(
    uint8_t *dst_p,
    const struct can_lib_bms_status_t *src_p,
    size_t size)
{
    uint16_t pack_current;

    if (size < 7u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 7);

    dst_p[0] |= pack_left_shift_u8(src_p->bms_state, 0u, 0x03u);
    dst_p[0] |= pack_left_shift_u16(src_p->bms_fault_code, 2u, 0xfcu);
    dst_p[1] |= pack_right_shift_u16(src_p->bms_fault_code, 6u, 0xffu);
    dst_p[2] |= pack_right_shift_u16(src_p->bms_fault_code, 14u, 0x03u);
    dst_p[2] |= pack_left_shift_u16(src_p->pack_voltage, 2u, 0xfcu);
    dst_p[3] |= pack_right_shift_u16(src_p->pack_voltage, 6u, 0xffu);
    dst_p[4] |= pack_right_shift_u16(src_p->pack_voltage, 14u, 0x03u);
    pack_current = (uint16_t)src_p->pack_current;
    dst_p[4] |= pack_left_shift_u16(pack_current, 2u, 0xfcu);
    dst_p[5] |= pack_right_shift_u16(pack_current, 6u, 0x3fu);
    dst_p[5] |= pack_left_shift_u8(src_p->cell_balancing_status, 6u, 0x40u);
    dst_p[5] |= pack_left_shift_u8(src_p->regen_enabled, 7u, 0x80u);
    dst_p[6] |= pack_left_shift_u8(src_p->overcurrent_detect, 0u, 0x01u);

    return (7);
}

int can_lib_bms_status_unpack(
    struct can_lib_bms_status_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    uint16_t pack_current;

    if (size < 7u) {
        return (-EINVAL);
    }

    dst_p->bms_state = unpack_right_shift_u8(src_p[0], 0u, 0x03u);
    dst_p->bms_fault_code = unpack_right_shift_u16(src_p[0], 2u, 0xfcu);
    dst_p->bms_fault_code |= unpack_left_shift_u16(src_p[1], 6u, 0xffu);
    dst_p->bms_fault_code |= unpack_left_shift_u16(src_p[2], 14u, 0x03u);
    dst_p->pack_voltage = unpack_right_shift_u16(src_p[2], 2u, 0xfcu);
    dst_p->pack_voltage |= unpack_left_shift_u16(src_p[3], 6u, 0xffu);
    dst_p->pack_voltage |= unpack_left_shift_u16(src_p[4], 14u, 0x03u);
    pack_current = unpack_right_shift_u16(src_p[4], 2u, 0xfcu);
    pack_current |= unpack_left_shift_u16(src_p[5], 6u, 0x3fu);

    if ((pack_current & (1u << 11)) != 0u) {
        pack_current |= 0xf000u;
    }

    dst_p->pack_current = (int16_t)pack_current;
    dst_p->cell_balancing_status = unpack_right_shift_u8(src_p[5], 6u, 0x40u);
    dst_p->regen_enabled = unpack_right_shift_u8(src_p[5], 7u, 0x80u);
    dst_p->overcurrent_detect = unpack_right_shift_u8(src_p[6], 0u, 0x01u);

    return (0);
}

int can_lib_bms_status_init(struct can_lib_bms_status_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct can_lib_bms_status_t));

    return 0;
}

uint8_t can_lib_bms_status_bms_state_encode(double value)
{
    return (uint8_t)(value);
}

double can_lib_bms_status_bms_state_decode(uint8_t value)
{
    return ((double)value);
}

bool can_lib_bms_status_bms_state_is_in_range(uint8_t value)
{
    return (value <= 3u);
}

uint16_t can_lib_bms_status_bms_fault_code_encode(double value)
{
    return (uint16_t)(value);
}

double can_lib_bms_status_bms_fault_code_decode(uint16_t value)
{
    return ((double)value);
}

bool can_lib_bms_status_bms_fault_code_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

uint16_t can_lib_bms_status_pack_voltage_encode(double value)
{
    return (uint16_t)(value);
}

double can_lib_bms_status_pack_voltage_decode(uint16_t value)
{
    return ((double)value);
}

bool can_lib_bms_status_pack_voltage_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

int16_t can_lib_bms_status_pack_current_encode(double value)
{
    return (int16_t)(value);
}

double can_lib_bms_status_pack_current_decode(int16_t value)
{
    return ((double)value);
}

bool can_lib_bms_status_pack_current_is_in_range(int16_t value)
{
    return ((value >= -2048) && (value <= 2047));
}

uint8_t can_lib_bms_status_cell_balancing_status_encode(double value)
{
    return (uint8_t)(value);
}

double can_lib_bms_status_cell_balancing_status_decode(uint8_t value)
{
    return ((double)value);
}

bool can_lib_bms_status_cell_balancing_status_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t can_lib_bms_status_regen_enabled_encode(double value)
{
    return (uint8_t)(value);
}

double can_lib_bms_status_regen_enabled_decode(uint8_t value)
{
    return ((double)value);
}

bool can_lib_bms_status_regen_enabled_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t can_lib_bms_status_overcurrent_detect_encode(double value)
{
    return (uint8_t)(value);
}

double can_lib_bms_status_overcurrent_detect_decode(uint8_t value)
{
    return ((double)value);
}

bool can_lib_bms_status_overcurrent_detect_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

int can_lib_bms_status_b_pack(
    uint8_t *dst_p,
    const struct can_lib_bms_status_b_t *src_p,
    size_t size)
{
    if (size < 1u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 1);

    dst_p[0] |= pack_left_shift_u8(src_p->bms_state_b, 0u, 0x03u);

    return (1);
}

int can_lib_bms_status_b_unpack(
    struct can_lib_bms_status_b_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 1u) {
        return (-EINVAL);
    }

    dst_p->bms_state_b = unpack_right_shift_u8(src_p[0], 0u, 0x03u);

    return (0);
}

int can_lib_bms_status_b_init(struct can_lib_bms_status_b_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct can_lib_bms_status_b_t));

    return 0;
}

uint8_t can_lib_bms_status_b_bms_state_b_encode(double value)
{
    return (uint8_t)(value);
}

double can_lib_bms_status_b_bms_state_b_decode(uint8_t value)
{
    return ((double)value);
}

bool can_lib_bms_status_b_bms_state_b_is_in_range(uint8_t value)
{
    return (value <= 3u);
}

int can_lib_bms_status_b_ex_pack(
    uint8_t *dst_p,
    const struct can_lib_bms_status_b_ex_t *src_p,
    size_t size)
{
    if (size < 1u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 1);

    dst_p[0] |= pack_left_shift_u8(src_p->bms_state_b, 0u, 0x03u);

    return (1);
}

int can_lib_bms_status_b_ex_unpack(
    struct can_lib_bms_status_b_ex_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 1u) {
        return (-EINVAL);
    }

    dst_p->bms_state_b = unpack_right_shift_u8(src_p[0], 0u, 0x03u);

    return (0);
}

int can_lib_bms_status_b_ex_init(struct can_lib_bms_status_b_ex_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct can_lib_bms_status_b_ex_t));

    return 0;
}

uint8_t can_lib_bms_status_b_ex_bms_state_b_encode(double value)
{
    return (uint8_t)(value);
}

double can_lib_bms_status_b_ex_bms_state_b_decode(uint8_t value)
{
    return ((double)value);
}

bool can_lib_bms_status_b_ex_bms_state_b_is_in_range(uint8_t value)
{
    return (value <= 3u);
}

int can_lib_bms_status_b_ex_e_pack(
    uint8_t *dst_p,
    const struct can_lib_bms_status_b_ex_e_t *src_p,
    size_t size)
{
    if (size < 1u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 1);

    dst_p[0] |= pack_left_shift_u8(src_p->bms_state_b, 0u, 0x03u);

    return (1);
}

int can_lib_bms_status_b_ex_e_unpack(
    struct can_lib_bms_status_b_ex_e_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 1u) {
        return (-EINVAL);
    }

    dst_p->bms_state_b = unpack_right_shift_u8(src_p[0], 0u, 0x03u);

    return (0);
}

int can_lib_bms_status_b_ex_e_init(struct can_lib_bms_status_b_ex_e_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct can_lib_bms_status_b_ex_e_t));

    return 0;
}

uint8_t can_lib_bms_status_b_ex_e_bms_state_b_encode(double value)
{
    return (uint8_t)(value);
}

double can_lib_bms_status_b_ex_e_bms_state_b_decode(uint8_t value)
{
    return ((double)value);
}

bool can_lib_bms_status_b_ex_e_bms_state_b_is_in_range(uint8_t value)
{
    return (value <= 3u);
}

int can_lib_charger_status_pack(
    uint8_t *dst_p,
    const struct can_lib_charger_status_t *src_p,
    size_t size)
{
    if (size < 6u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 6);

    dst_p[0] |= pack_left_shift_u8(src_p->charger_state, 0u, 0x07u);
    dst_p[0] |= pack_left_shift_u16(src_p->voltage_target, 3u, 0xf8u);
    dst_p[1] |= pack_right_shift_u16(src_p->voltage_target, 5u, 0xffu);
    dst_p[2] |= pack_right_shift_u16(src_p->voltage_target, 13u, 0x07u);
    dst_p[2] |= pack_left_shift_u16(src_p->output_voltage, 3u, 0xf8u);
    dst_p[3] |= pack_right_shift_u16(src_p->output_voltage, 5u, 0xffu);
    dst_p[4] |= pack_right_shift_u16(src_p->output_voltage, 13u, 0x07u);
    dst_p[4] |= pack_left_shift_u16(src_p->output_current, 3u, 0xf8u);
    dst_p[5] |= pack_right_shift_u16(src_p->output_current, 5u, 0x1fu);

    return (6);
}

int can_lib_charger_status_unpack(
    struct can_lib_charger_status_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 6u) {
        return (-EINVAL);
    }

    dst_p->charger_state = unpack_right_shift_u8(src_p[0], 0u, 0x07u);
    dst_p->voltage_target = unpack_right_shift_u16(src_p[0], 3u, 0xf8u);
    dst_p->voltage_target |= unpack_left_shift_u16(src_p[1], 5u, 0xffu);
    dst_p->voltage_target |= unpack_left_shift_u16(src_p[2], 13u, 0x07u);
    dst_p->output_voltage = unpack_right_shift_u16(src_p[2], 3u, 0xf8u);
    dst_p->output_voltage |= unpack_left_shift_u16(src_p[3], 5u, 0xffu);
    dst_p->output_voltage |= unpack_left_shift_u16(src_p[4], 13u, 0x07u);
    dst_p->output_current = unpack_right_shift_u16(src_p[4], 3u, 0xf8u);
    dst_p->output_current |= unpack_left_shift_u16(src_p[5], 5u, 0x1fu);

    return (0);
}

int can_lib_charger_status_init(struct can_lib_charger_status_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct can_lib_charger_status_t));

    return 0;
}

uint8_t can_lib_charger_status_charger_state_encode(double value)
{
    return (uint8_t)(value);
}

double can_lib_charger_status_charger_state_decode(uint8_t value)
{
    return ((double)value);
}

bool can_lib_charger_status_charger_state_is_in_range(uint8_t value)
{
    return (value <= 7u);
}

uint16_t can_lib_charger_status_voltage_target_encode(double value)
{
    return (uint16_t)(value);
}

double can_lib_charger_status_voltage_target_decode(uint16_t value)
{
    return ((double)value);
}

bool can_lib_charger_status_voltage_target_is_in_range(uint16_t value)
{
    return (value <= 70u);
}

uint16_t can_lib_charger_status_output_voltage_encode(double value)
{
    return (uint16_t)(value);
}

double can_lib_charger_status_output_voltage_decode(uint16_t value)
{
    return ((double)value);
}

bool can_lib_charger_status_output_voltage_is_in_range(uint16_t value)
{
    return (value <= 70u);
}

uint16_t can_lib_charger_status_output_current_encode(double value)
{
    return (uint16_t)(value);
}

double can_lib_charger_status_output_current_decode(uint16_t value)
{
    return ((double)value);
}

bool can_lib_charger_status_output_current_is_in_range(uint16_t value)
{
    return (value <= 100u);
}
