/**
 * @file octal.c
 *
 * @brief This source file was generated by cantools version 40.7.1 Sun Dec 21 23:45:56 2025.
 *
 * @copyright Copyright (c) 2018-2019 Erik Moqvist
 *
 * @par License
 * The MIT License (MIT)
 *
 * Permission is hereby granted, free of charge, to any person
 * obtaining a copy of this software and associated documentation
 * files (the "Software"), to deal in the Software without
 * restriction, including without limitation the rights to use, copy,
 * modify, merge, publish, distribute, sublicense, and/or sell copies
 * of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be
 * included in all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 * NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS
 * BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN
 * ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
 * CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

#include <string.h>

#include "octal.h"

static inline uint8_t pack_left_shift_u8(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value << shift) & mask);
}

static inline uint8_t unpack_right_shift_u8(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value & mask) >> shift);
}

int octal_status_pack(
    uint8_t *dst_p,
    const struct octal_status_t *src_p,
    size_t size)
{
    uint8_t bms_ok;

    if (size < 7u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 7);

    bms_ok = (uint8_t)src_p->bms_ok;
    dst_p[0] |= pack_left_shift_u8(bms_ok, 0u, 0x01u);

    return (7);
}

int octal_status_unpack(
    struct octal_status_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    uint8_t bms_ok;

    if (size < 7u) {
        return (-EINVAL);
    }

    bms_ok = unpack_right_shift_u8(src_p[0], 0u, 0x01u);

    if ((bms_ok & (1u << 0)) != 0u) {
        bms_ok |= 0xfeu;
    }

    dst_p->bms_ok = (int8_t)bms_ok;

    return (0);
}

int octal_status_init(struct octal_status_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct octal_status_t));

    return 0;
}

int8_t octal_status_bms_ok_encode(float value)
{
    return (int8_t)(value);
}

float octal_status_bms_ok_decode(int8_t value)
{
    return ((float)value);
}

bool octal_status_bms_ok_is_in_range(int8_t value)
{
    return ((value >= 0) && (value <= 1));
}
